-- SET CURRENT SCHEMA = 'CWSRS1' ;

DROP VIEW VW_LST_PARENT_CASE_HIST;

CREATE VIEW VW_LST_PARENT_CASE_HIST AS
SELECT DISTINCT 
    v2.PARENT_ID AS PARENT_PERSON_ID,
	v1.CASE_ID,
	v1.START_DATE,
	v1.END_DATE,
	v1.COUNTY,
	v1.SERVICE_COMP,
	v1.LIMITED_ACCESS_CODE,
	v1.LIMITED_ACCESS_DATE,
	v1.LIMITED_ACCESS_DESCRIPTION,
	v1.LIMITED_ACCESS_GOVERNMENT_ENT,
	v1.CASE_LAST_UPDATED,
	v1.FOCUS_CHLD_FIRST_NM,
	v1.FOCUS_CHLD_LAST_NM,
	v1.FOCUS_CHILD_ID,
	v1.FOCUS_CHILD_SENSITIVITY_IND,
	v1.FOCUS_CHILD_LAST_UPDATED,
	v1.PARENT_FIRST_NM,
	v1.PARENT_LAST_NM,
	v1.PARENT_RELATIONSHIP,
	v1.PARENT_ID,
	v1.PARENT_SENSITIVITY_IND,
	v1.PARENT_LAST_UPDATED,
	v1.PARENT_SOURCE_TABLE,
	v1.WORKER_FIRST_NM,
	v1.WORKER_LAST_NM,
	v1.WORKER_ID,
	v1.WORKER_LAST_UPDATED,
	v1.CAS_IBMSNAP_LOGMARKER,
	v1.CAS_IBMSNAP_OPERATION,
	v1.CLC_IBMSNAP_LOGMARKER,
	v1.CLC_IBMSNAP_OPERATION,
	v1.CLP_IBMSNAP_LOGMARKER,
	v1.CLP_IBMSNAP_OPERATION,
	v1.STF_IBMSNAP_LOGMARKER,
	v1.STF_IBMSNAP_OPERATION,
	v1.LAST_CHG
FROM VW_LST_CASE_HIST v1 
JOIN VW_LST_CASE_HIST v2 ON v1.CASE_ID = v2.CASE_ID;

COMMIT;
