-- SET CURRENT SCHEMA = 'CWSRS1' ;

DROP VIEW VW_MQT_PARENT_CASE_HIST;

CREATE VIEW VW_MQT_PARENT_CASE_HIST AS
SELECT DISTINCT v2.PARENT_ID AS PARENT_PERSON_ID, v1.* 
FROM MQT_CASE_HIST v1 
JOIN MQT_CASE_HIST v2 ON v1.CASE_ID = v2.CASE_ID;

COMMIT;
