SET CURRENT SCHEMA = 'CWSRSQ';


--DROP TABLE MQT_CLIENT_ADDRESS;
--
--COMMIT;
--
--DROP TABLE MQT_CASE_HIST;
--
--COMMIT;
--
--DROP TABLE MQT_OTHER_CLIENT_NAME;
--
--COMMIT;
--
--DROP TABLE MQT_REL_CLN_RELT_CLIENT ;
--
--COMMIT;
--
--
--
--DROP VIEW VW_LST_REFERRAL_HIST;
--
--COMMIT;
--
--DROP VIEW VW_LST_BI_DIR_RELATION;
--
--COMMIT;
--
--DROP VIEW VW_LST_CASE_HIST;
--
--COMMIT;
--
--DROP VIEW VW_LST_CLIENT_ADDRESS;
--
--COMMIT;
--
--DROP VIEW VW_LST_OTHER_CLIENT_NAME;
--
--COMMIT;
--
--DROP VIEW VW_LST_REL_CLN_RELT_CLIENT;
--
--COMMIT;
--
--DROP VIEW VW_MQT_BI_DIR_RELATION;
--
--COMMIT;
--
--DROP VIEW VW_MQT_PARENT_CASE_HIST;
--
--COMMIT;
--


DROP TABLE GT_ID;

CREATE GLOBAL TEMPORARY TABLE GT_ID ( 
	IDENTIFIER	CHAR(10) NOT NULL
);

COMMIT;


DROP TABLE GT_REFR_CLT;

CREATE GLOBAL TEMPORARY TABLE GT_REFR_CLT ( 
	FKREFERL_T  CHAR(10) NOT NULL,
	FKCLIENT_T  CHAR(10) NOT NULL,
	SENSTV_IND 	CHAR(1)  NOT NULL
);

COMMIT;




CREATE TABLE MQT_CLIENT_ADDRESS AS (
	SELECT
	  clt.IDENTIFIER AS CLT_IDENTIFIER,
	  clt.LST_UPD_ID AS CLT_LST_UPD_ID,
	  clt.LST_UPD_TS AS CLT_LST_UPD_TS,
	  clt.ADJDEL_IND AS CLT_ADJDEL_IND,
	  clt.ADPTN_STCD AS CLT_ADPTN_STCD,
	  clt.ALN_REG_NO AS CLT_ALN_REG_NO,
	  clt.BIRTH_CITY AS CLT_BIRTH_CITY,
	  clt.B_CNTRY_C  AS CLT_B_CNTRY_C, 
	  clt.BIRTH_DT   AS CLT_BIRTH_DT,  
	  clt.BR_FAC_NM  AS CLT_BR_FAC_NM, 
	  clt.B_STATE_C  AS CLT_B_STATE_C, 
	  clt.BP_VER_IND AS CLT_BP_VER_IND,
	  clt.CHLD_CLT_B AS CLT_CHLD_CLT_B,
	  clt.CL_INDX_NO AS CLT_CL_INDX_NO,
	  clt.COMMNT_DSC AS CLT_COMMNT_DSC,
	  clt.COM_FST_NM AS CLT_COM_FST_NM,
	  clt.COM_LST_NM AS CLT_COM_LST_NM,
	  clt.COM_MID_NM AS CLT_COM_MID_NM,
	  clt.CONF_ACTDT AS CLT_CONF_ACTDT,
	  clt.CONF_EFIND AS CLT_CONF_EFIND,
	  clt.CREATN_DT  AS CLT_CREATN_DT, 
	  clt.CURRCA_IND AS CLT_CURRCA_IND,
	  clt.COTH_DESC  AS CLT_COTH_DESC, 
	  clt.CURREG_IND AS CLT_CURREG_IND,
	  clt.DEATH_DT   AS CLT_DEATH_DT,  
	  clt.DTH_DT_IND AS CLT_DTH_DT_IND,
	  clt.DEATH_PLC  AS CLT_DEATH_PLC, 
	  clt.DTH_RN_TXT AS CLT_DTH_RN_TXT,
	  clt.DRV_LIC_NO AS CLT_DRV_LIC_NO,
	  clt.D_STATE_C  AS CLT_D_STATE_C, 
	  clt.EMAIL_ADDR AS CLT_EMAIL_ADDR,
	  clt.EST_DOB_CD AS CLT_EST_DOB_CD,
	  clt.ETH_UD_CD  AS CLT_ETH_UD_CD, 
	  clt.FTERM_DT   AS CLT_FTERM_DT,  
	  clt.GENDER_CD  AS CLT_GENDER_CD, 
	  clt.HEALTH_TXT AS CLT_HEALTH_TXT,
	  clt.HISP_UD_CD AS CLT_HISP_UD_CD,
	  clt.HISP_CD    AS CLT_HISP_CD,   
	  clt.I_CNTRY_C  AS CLT_I_CNTRY_C, 
	  clt.IMGT_STC   AS CLT_IMGT_STC,  
	  clt.INCAPC_CD  AS CLT_INCAPC_CD, 
	  clt.HCARE_IND  AS CLT_HCARE_IND, 
	  clt.LIMIT_IND  AS CLT_LIMIT_IND, 
	  clt.LITRATE_CD AS CLT_LITRATE_CD,
	  clt.MAR_HIST_B AS CLT_MAR_HIST_B,
	  clt.MRTL_STC   AS CLT_MRTL_STC,  
	  clt.MILT_STACD AS CLT_MILT_STACD,
	  clt.MTERM_DT   AS CLT_MTERM_DT,  
	  clt.NMPRFX_DSC AS CLT_NMPRFX_DSC,
	  clt.NAME_TPC   AS CLT_NAME_TPC,  
	  clt.OUTWRT_IND AS CLT_OUTWRT_IND,
	  clt.PREVCA_IND AS CLT_PREVCA_IND,
	  clt.POTH_DESC  AS CLT_POTH_DESC, 
	  clt.PREREG_IND AS CLT_PREREG_IND,
	  clt.P_ETHNCTYC AS CLT_P_ETHNCTYC,
	  clt.P_LANG_TPC AS CLT_P_LANG_TPC,
	  clt.RLGN_TPC   AS CLT_RLGN_TPC,  
	  clt.S_LANG_TC  AS CLT_S_LANG_TC, 
	  clt.SNTV_HLIND AS CLT_SNTV_HLIND,
	  clt.SENSTV_IND AS CLT_SENSTV_IND,
	  clt.SOCPLC_CD  AS CLT_SOCPLC_CD, 
	  clt.SOC158_IND AS CLT_SOC158_IND,
	  clt.SSN_CHG_CD AS CLT_SSN_CHG_CD,
	  clt.SS_NO      AS CLT_SS_NO,    
	  clt.SUFX_TLDSC AS CLT_SUFX_TLDSC,
	  clt.TRBA_CLT_B AS CLT_TRBA_CLT_B,
	  clt.TR_MBVRT_B AS CLT_TR_MBVRT_B,
	  clt.UNEMPLY_CD AS CLT_UNEMPLY_CD,
	  clt.ZIPPY_IND  AS CLT_ZIPPY_IND, 
	  clt.IBMSNAP_LOGMARKER AS CLT_IBMSNAP_LOGMARKER,
	  clt.IBMSNAP_OPERATION AS CLT_IBMSNAP_OPERATION,
	  cla.IDENTIFIER AS CLA_IDENTIFIER,
	  cla.LST_UPD_ID AS CLA_LST_UPD_ID,
	  cla.LST_UPD_TS AS CLA_LST_UPD_TS,
	  cla.ADDR_TPC   AS CLA_ADDR_TPC,  
	  cla.BK_INMT_ID AS CLA_BK_INMT_ID,
	  cla.EFF_END_DT AS CLA_EFF_END_DT,
	  cla.EFF_STRTDT AS CLA_EFF_STRTDT,
	  cla.FKADDRS_T  AS CLA_FKADDRS_T, 
	  cla.FKCLIENT_T AS CLA_FKCLIENT_T,
	  cla.FKREFERL_T AS CLA_FKREFERL_T,
	  cla.HOMLES_IND AS CLA_HOMLES_IND,
	  cla.IBMSNAP_LOGMARKER AS CLA_IBMSNAP_LOGMARKER,
	  cla.IBMSNAP_OPERATION AS CLA_IBMSNAP_OPERATION,
	  adr.IDENTIFIER        AS ADR_IDENTIFIER,
	  adr.LST_UPD_ID        AS ADR_LST_UPD_ID,
	  adr.LST_UPD_TS        AS ADR_LST_UPD_TS,
	  TRIM(adr.ADDR_DSC)    AS ADR_ADDR_DSC,
	  TRIM(adr.CITY_NM)     AS ADR_CITY_NM,
	  adr.EMRG_EXTNO        AS ADR_EMRG_EXTNO,
	  adr.EMRG_TELNO        AS ADR_EMRG_TELNO,
	  adr.FRG_ADRT_B        AS ADR_FRG_ADRT_B,
	  adr.GVR_ENTC          AS ADR_GVR_ENTC,  
	  TRIM(adr.HEADER_ADR)  AS ADR_HEADER_ADR,
	  adr.MSG_EXT_NO        AS ADR_MSG_EXT_NO,
	  adr.MSG_TEL_NO        AS ADR_MSG_TEL_NO,
	  TRIM(adr.POSTDIR_CD)  AS ADR_POSTDIR_CD,
	  TRIM(adr.PREDIR_CD)   AS ADR_PREDIR_CD,
	  adr.PRM_EXT_NO        AS ADR_PRM_EXT_NO,
	  adr.PRM_TEL_NO        AS ADR_PRM_TEL_NO,
	  adr.STATE_C           AS ADR_STATE_C,   
	  TRIM(adr.STREET_NM)   AS ADR_STREET_NM,
	  TRIM(adr.STREET_NO)   AS ADR_STREET_NO,
	  adr.ST_SFX_C          AS ADR_ST_SFX_C,
	  adr.UNT_DSGC          AS ADR_UNT_DSGC,
	  TRIM(adr.UNIT_NO)     AS ADR_UNIT_NO,
	  TRIM(adr.ZIP_NO)      AS ADR_ZIP_NO,
	  adr.ZIP_SFX_NO        AS ADR_ZIP_SFX_NO,
	  adr.IBMSNAP_LOGMARKER AS ADR_IBMSNAP_LOGMARKER,
	  adr.IBMSNAP_OPERATION AS ADR_IBMSNAP_OPERATION,
	  MAX (
	    clt.IBMSNAP_LOGMARKER, 
	    NVL(cla.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
	    NVL(adr.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40'))
	  ) last_chg
	  FROM CLIENT_T clt
	  LEFT JOIN CL_ADDRT cla ON clt.IDENTIFIER = cla.FKCLIENT_T
	  LEFT JOIN ADDRS_T  adr ON cla.FKADDRS_T  = adr.IDENTIFIER
	  ORDER BY clt_IDENTIFIER
)
DATA INITIALLY DEFERRED
REFRESH DEFERRED
DISABLE QUERY OPTIMIZATION;

COMMIT;


CREATE TABLE MQT_CASE_HIST AS (
	SELECT
	  CAS.IDENTIFIER AS CASE_ID,
	  CAS.START_DT   AS START_DATE,
	  CAS.END_DT     AS END_DATE,
	  CAS.GVR_ENTC   AS COUNTY,
	  CAS.SRV_CMPC   AS SERVICE_COMP,
	  CAS.LMT_ACSSCD AS LIMITED_ACCESS_CODE,
	  CAS.LMT_ACS_DT AS LIMITED_ACCESS_DATE,
	  CAS.LMT_ACSDSC AS LIMITED_ACCESS_DESCRIPTION,
	  CAS.L_GVR_ENTC AS LIMITED_ACCESS_GOVERNMENT_ENT,
	  CAS.LST_UPD_TS AS CASE_LAST_UPDATED,
	  CLC.COM_FST_NM AS FOCUS_CHLD_FIRST_NM,
	  CLC.COM_LST_NM AS FOCUS_CHLD_LAST_NM,
	  CLC.IDENTIFIER AS FOCUS_CHILD_ID,
	  CLC.SENSTV_IND AS FOCUS_CHILD_SENSITIVITY_IND,
	  CLC.LST_UPD_TS AS FOCUS_CHILD_LAST_UPDATED,
	  CLP.COM_FST_NM AS PARENT_FIRST_NM,
	  CLP.COM_LST_NM AS PARENT_LAST_NM,
	  CLR.CLNTRELC   AS PARENT_RELATIONSHIP,
	  CLP.IDENTIFIER AS PARENT_ID,
	  CLP.SENSTV_IND AS PARENT_SENSITIVITY_IND,
	  CLP.LST_UPD_TS AS PARENT_LAST_UPDATED,
	  'CLIENT_T'     AS PARENT_SOURCE_TABLE,
	  STF.FIRST_NM   AS WORKER_FIRST_NM,
	  STF.LAST_NM    AS WORKER_LAST_NM,
	  STF.IDENTIFIER AS WORKER_ID,
	  STF.LST_UPD_TS AS WORKER_LAST_UPDATED,  
	  CAS.IBMSNAP_LOGMARKER AS CAS_IBMSNAP_LOGMARKER,
	  CAS.IBMSNAP_OPERATION AS CAS_IBMSNAP_OPERATION,
	  CLC.IBMSNAP_LOGMARKER AS CLC_IBMSNAP_LOGMARKER,
	  CLC.IBMSNAP_OPERATION AS CLC_IBMSNAP_OPERATION,
	  CLP.IBMSNAP_LOGMARKER AS CLP_IBMSNAP_LOGMARKER,
	  CLP.IBMSNAP_OPERATION AS CLP_IBMSNAP_OPERATION,
	  STF.IBMSNAP_LOGMARKER AS STF_IBMSNAP_LOGMARKER,
	  STF.IBMSNAP_OPERATION AS STF_IBMSNAP_OPERATION,
	  MAX (
	    NVL(CAS.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
	    NVL(CLC.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
	    NVL(CLP.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40'))    
	  ) LAST_CHG
	FROM CASE_T CAS
	LEFT JOIN CHLD_CLT CCL ON CCL.FKCLIENT_T = CAS.FKCHLD_CLT
	LEFT JOIN CLIENT_T CLC ON CLC.IDENTIFIER = CCL.FKCLIENT_T
	JOIN CLN_RELT CLR ON CLR.FKCLIENT_0 = CCL.FKCLIENT_T AND ((CLR.CLNTRELC BETWEEN 187 and 214) OR
	(CLR.CLNTRELC BETWEEN 245 and 254) OR (CLR.CLNTRELC BETWEEN 282 and 294) OR (CLR.CLNTRELC IN (272, 273, 5620, 6360, 6361)))
	JOIN CLIENT_T CLP ON CLP.IDENTIFIER = CLR.FKCLIENT_T
	LEFT JOIN STFPERST STF ON STF.IDENTIFIER = CAS.FKSTFPERST
	UNION
	SELECT
	  CAS.IDENTIFIER AS CASE_ID,
	  CAS.START_DT   AS START_DATE,
	  CAS.END_DT     AS END_DATE,
	  CAS.GVR_ENTC   AS COUNTY,
	  CAS.SRV_CMPC   AS SERVICE_COMP,
	  CAS.LMT_ACSSCD AS LIMITED_ACCESS_CODE,
	  CAS.LMT_ACS_DT AS LIMITED_ACCESS_DATE,
	  CAS.LMT_ACSDSC AS LIMITED_ACCESS_DESCRIPTION,
	  CAS.L_GVR_ENTC AS LIMITED_ACCESS_GOVERNMENT_ENT,
	  CAS.LST_UPD_TS AS CASE_LAST_UPDATED,
	  CLC.COM_FST_NM AS FOCUS_CHLD_FIRST_NM,
	  CLC.COM_LST_NM AS FOCUS_CHLD_LAST_NM,
	  CLC.IDENTIFIER AS FOCUS_CHILD_ID,
	  CLC.SENSTV_IND AS FOCUS_CHILD_SENSITIVITY_IND,
	  CLC.LST_UPD_TS AS FOCUS_CHILD_LAST_UPDATED,
	  CLP.COM_FST_NM AS PARENT_FIRST_NM,
	  CLP.COM_LST_NM AS PARENT_LAST_NM,
	  CLR.CLNTRELC   AS PARENT_RELATIONSHIP,
	  CLP.IDENTIFIER AS PARENT_ID,
	  CLP.SENSTV_IND AS PARENT_SENSITIVITY_IND,
	  CLP.LST_UPD_TS AS PARENT_LAST_UPDATED,
	  'CLIENT_T'     AS PARENT_SOURCE_TABLE,
	  STF.FIRST_NM   AS WORKER_FIRST_NM,
	  STF.LAST_NM    AS WORKER_LAST_NM,
	  STF.IDENTIFIER AS WORKER_ID,
	  STF.LST_UPD_TS AS WORKER_LAST_UPDATED,  
	  CAS.IBMSNAP_LOGMARKER AS CAS_IBMSNAP_LOGMARKER,
	  CAS.IBMSNAP_OPERATION AS CAS_IBMSNAP_OPERATION,
	  CLC.IBMSNAP_LOGMARKER AS CLC_IBMSNAP_LOGMARKER,
	  CLC.IBMSNAP_OPERATION AS CLC_IBMSNAP_OPERATION,
	  CLP.IBMSNAP_LOGMARKER AS CLP_IBMSNAP_LOGMARKER,
	  CLP.IBMSNAP_OPERATION AS CLP_IBMSNAP_OPERATION,
	  STF.IBMSNAP_LOGMARKER AS STF_IBMSNAP_LOGMARKER,
	  STF.IBMSNAP_OPERATION AS STF_IBMSNAP_OPERATION,
	  MAX (
	    NVL(CAS.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
	    NVL(CLC.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
	    NVL(CLP.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40'))    
	  ) LAST_CHG
	FROM CASE_T CAS
	LEFT JOIN CHLD_CLT CCL ON CCL.FKCLIENT_T = CAS.FKCHLD_CLT
	LEFT JOIN CLIENT_T CLC ON CLC.IDENTIFIER = CCL.FKCLIENT_T
	JOIN CLN_RELT CLR ON CLR.FKCLIENT_T = CCL.FKCLIENT_T AND ((CLR.CLNTRELC BETWEEN 187 and 214) OR
	(CLR.CLNTRELC BETWEEN 245 and 254) OR (CLR.CLNTRELC BETWEEN 282 and 294) OR (CLR.CLNTRELC IN (272, 273, 5620, 6360, 6361)))
	JOIN CLIENT_T CLP ON CLP.IDENTIFIER = CLR.FKCLIENT_0
	LEFT JOIN STFPERST STF ON STF.IDENTIFIER = CAS.FKSTFPERST
)
DATA INITIALLY DEFERRED
REFRESH DEFERRED
DISABLE QUERY OPTIMIZATION;

COMMIT;


CREATE TABLE MQT_OTHER_CLIENT_NAME AS (
	SELECT
	  ONM.THIRD_ID AS THIRD_ID,
	  ONM.FIRST_NM AS FIRST_NM,
	  ONM.LAST_NM AS LAST_NM,
	  ONM.MIDDLE_NM AS MIDDLE_NM,
	  ONM.NMPRFX_DSC AS NMPRFX_DSC,
	  ONM.NAME_TPC AS NAME_TPC,
	  ONM.SUFX_TLDSC AS SUFX_TLDSC,
	  ONM.LST_UPD_ID AS LST_UPD_ID,
	  ONM.LST_UPD_TS AS LST_UPD_TS,
	  ONM.FKCLIENT_T AS FKCLIENT_T,
	  ONM.IBMSNAP_OPERATION AS IBMSNAP_OPERATION,
	  ONM.IBMSNAP_LOGMARKER AS IBMSNAP_LOGMARKER,
	  CLT.SENSTV_IND AS CLIENT_SENSITIVITY_IND,
	  MAX(ONM.IBMSNAP_LOGMARKER, CLT.IBMSNAP_LOGMARKER) LAST_CHG
	FROM OCL_NM_T ONM
	JOIN CLIENT_T CLT ON CLT.IDENTIFIER = ONM.FKCLIENT_T
	ORDER BY FKCLIENT_T
)
DATA INITIALLY DEFERRED
REFRESH DEFERRED
DISABLE QUERY OPTIMIZATION;

COMMIT;


CREATE TABLE MQT_REL_CLN_RELT_CLIENT AS (
      SELECT
            'CLN_RELT'              AS THIS_LEGACY_TABLE,
            'CLIENT_T'              AS RELATED_LEGACY_TABLE,
            CLNS.IDENTIFIER         AS THIS_LEGACY_ID,
            CLNS.SENSTV_IND         AS THIS_SENSITIVITY_IND,            
            CLNS.LST_UPD_ID         AS THIS_LEGACY_LAST_UPDATED_ID,
            CLNS.LST_UPD_TS         AS THIS_LEGACY_LAST_UPDATED,                                    
            CLNS.COM_FST_NM         AS THIS_FIRST_NAME,
            CLNS.COM_LST_NM         AS THIS_LAST_NAME,
            CLNR.CLNTRELC           AS REL_CODE,
            CLNP.IDENTIFIER         AS RELATED_LEGACY_ID,
            CLNP.SENSTV_IND         AS RELATED_SENSITIVITY_IND,            
            CLNP.LST_UPD_ID         AS RELATED_LEGACY_LAST_UPDATED_ID,
            CLNP.LST_UPD_TS         AS RELATED_LEGACY_LAST_UPDATED,                        
            CLNP.COM_FST_NM         AS RELATED_FIRST_NAME,
            CLNP.COM_LST_NM         AS RELATED_LAST_NAME,            
            CLNS.IBMSNAP_LOGMARKER  AS THIS_IBMSNAP_LOGMARKER,
            CLNS.IBMSNAP_OPERATION  AS THIS_IBMSNAP_OPERATION,
            CLNP.IBMSNAP_LOGMARKER  AS RELATED_IBMSNAP_LOGMARKER,
            CLNP.IBMSNAP_OPERATION  AS RELATED_IBMSNAP_OPERATION,            
            MAX(CLNR.IBMSNAP_LOGMARKER, CLNP.IBMSNAP_LOGMARKER, CLNS.IBMSNAP_LOGMARKER) AS LAST_CHG
      FROM CLN_RELT CLNR
      JOIN CLIENT_T CLNS     ON CLNR.FKCLIENT_T = CLNS.IDENTIFIER
      JOIN CLIENT_T CLNP     ON CLNR.FKCLIENT_0 = CLNP.IDENTIFIER
)
DATA INITIALLY DEFERRED
REFRESH DEFERRED
DISABLE QUERY OPTIMIZATION;

COMMIT;




CREATE VIEW VW_LST_REL_CLN_RELT_CLIENT (
  THIS_LEGACY_TABLE,
  RELATED_LEGACY_TABLE, 
  THIS_LEGACY_ID,
  THIS_SENSITIVITY_IND,
  THIS_LEGACY_LAST_UPDATED_ID,
  THIS_LEGACY_LAST_UPDATED,
  THIS_FIRST_NAME,
  THIS_LAST_NAME,
  REL_CODE,
  RELATED_LEGACY_ID,
  RELATED_SENSITIVITY_IND,
  RELATED_LEGACY_LAST_UPDATED_ID,
  RELATED_LEGACY_LAST_UPDATED,
  RELATED_FIRST_NAME,
  RELATED_LAST_NAME,
  THIS_IBMSNAP_LOGMARKER,
  THIS_IBMSNAP_OPERATION,
  RELATED_IBMSNAP_LOGMARKER,
  RELATED_IBMSNAP_OPERATION,
  LAST_CHG
) AS
SELECT
    'CLN_RELT'              AS THIS_LEGACY_TABLE,
    'CLIENT_T'              AS RELATED_LEGACY_TABLE,
    CLNS.IDENTIFIER         AS THIS_LEGACY_ID,
    CLNS.SENSTV_IND         AS THIS_SENSITIVITY_IND,
    CLNS.LST_UPD_ID         AS THIS_LEGACY_LAST_UPDATED_ID,
    CLNS.LST_UPD_TS         AS THIS_LEGACY_LAST_UPDATED,
    CLNS.COM_FST_NM         AS THIS_FIRST_NAME,
    CLNS.COM_LST_NM         AS THIS_LAST_NAME,
    CLNR.CLNTRELC           AS REL_CODE,
    CLNP.IDENTIFIER         AS RELATED_LEGACY_ID,
    CLNP.SENSTV_IND         AS RELATED_SENSITIVITY_IND,
    CLNP.LST_UPD_ID         AS RELATED_LEGACY_LAST_UPDATED_ID,
    CLNP.LST_UPD_TS         AS RELATED_LEGACY_LAST_UPDATED,
    CLNP.COM_FST_NM         AS RELATED_FIRST_NAME,
    CLNP.COM_LST_NM         AS RELATED_LAST_NAME,
    CLNS.IBMSNAP_LOGMARKER  AS THIS_IBMSNAP_LOGMARKER,
    CLNS.IBMSNAP_OPERATION  AS THIS_IBMSNAP_OPERATION,
    CLNP.IBMSNAP_LOGMARKER  AS RELATED_IBMSNAP_LOGMARKER,
    CLNP.IBMSNAP_OPERATION  AS RELATED_IBMSNAP_OPERATION,
    MAX (
      CLNR.IBMSNAP_LOGMARKER,
      CLNP.IBMSNAP_LOGMARKER,
      CLNS.IBMSNAP_LOGMARKER
    ) AS LAST_CHG
FROM CLN_RELT CLNR
JOIN CLIENT_T CLNS ON CLNR.FKCLIENT_T = CLNS.IDENTIFIER
JOIN CLIENT_T CLNP ON CLNR.FKCLIENT_0 = CLNP.IDENTIFIER
WHERE CLNR.IDENTIFIER IN (
	SELECT GT.IDENTIFIER FROM GT_ID GT
);

COMMIT;


CREATE VIEW VW_LST_BI_DIR_RELATION (
  REVERSE_RELATIONSHIP,
  THIS_LEGACY_ID,
  THIS_SENSITIVITY_IND,
  THIS_LEGACY_LAST_UPDATED,
  THIS_LEGACY_LAST_UPDATED_ID,
  THIS_FIRST_NAME,
  THIS_LAST_NAME,
  REL_CODE,
  RELATED_LEGACY_ID,
  RELATED_SENSITIVITY_IND,
  RELATED_LEGACY_LAST_UPDATED,
  RELATED_LEGACY_LAST_UPDATED_ID,
  RELATED_FIRST_NAME,
  RELATED_LAST_NAME,
  THIS_IBMSNAP_LOGMARKER,
  THIS_IBMSNAP_OPERATION,
  RELATED_IBMSNAP_LOGMARKER,
  RELATED_IBMSNAP_OPERATION,
  LAST_CHG
) AS
SELECT
  0 AS REVERSE_RELATIONSHIP,
  v.THIS_LEGACY_ID,
  v.THIS_SENSITIVITY_IND,
  v.THIS_LEGACY_LAST_UPDATED,
  v.THIS_LEGACY_LAST_UPDATED_ID,
  v.THIS_FIRST_NAME,
  v.THIS_LAST_NAME,
  v.REL_CODE,
  v.RELATED_LEGACY_ID,
  v.RELATED_SENSITIVITY_IND,
  v.RELATED_LEGACY_LAST_UPDATED,
  v.RELATED_LEGACY_LAST_UPDATED_ID,
  v.RELATED_FIRST_NAME,
  v.RELATED_LAST_NAME,
  v.THIS_IBMSNAP_LOGMARKER,
  v.THIS_IBMSNAP_OPERATION,
  v.RELATED_IBMSNAP_LOGMARKER,
  v.RELATED_IBMSNAP_OPERATION,
  v.LAST_CHG
FROM VW_LST_REL_CLN_RELT_CLIENT v
UNION ALL
SELECT
  1 AS REVERSE_RELATIONSHIP,
  v.RELATED_LEGACY_ID,
  v.RELATED_SENSITIVITY_IND,
  v.RELATED_LEGACY_LAST_UPDATED,
  v.RELATED_LEGACY_LAST_UPDATED_ID,
  v.RELATED_FIRST_NAME,
  v.RELATED_LAST_NAME,
  v.REL_CODE,
  v.THIS_LEGACY_ID,
  v.THIS_SENSITIVITY_IND,
  v.THIS_LEGACY_LAST_UPDATED,
  v.THIS_LEGACY_LAST_UPDATED_ID,
  v.THIS_FIRST_NAME,
  v.THIS_LAST_NAME,
  v.THIS_IBMSNAP_LOGMARKER,
  v.THIS_IBMSNAP_OPERATION,
  v.RELATED_IBMSNAP_LOGMARKER,
  v.RELATED_IBMSNAP_OPERATION,
  v.LAST_CHG
FROM VW_LST_REL_CLN_RELT_CLIENT v;

COMMIT;


CREATE VIEW VW_LST_CASE_HIST (
  CASE_ID,
  START_DATE,
  END_DATE,
  COUNTY,
  SERVICE_COMP,
  LIMITED_ACCESS_CODE,
  LIMITED_ACCESS_DATE,
  LIMITED_ACCESS_DESCRIPTION,
  LIMITED_ACCESS_GOVERNMENT_ENT,
  CASE_LAST_UPDATED,
  FOCUS_CHLD_FIRST_NM,
  FOCUS_CHLD_LAST_NM,
  FOCUS_CHILD_ID,
  FOCUS_CHILD_SENSITIVITY_IND,
  FOCUS_CHILD_LAST_UPDATED,
  PARENT_FIRST_NM,
  PARENT_LAST_NM,
  PARENT_RELATIONSHIP,
  PARENT_ID,
  PARENT_SENSITIVITY_IND,
  PARENT_LAST_UPDATED,
  PARENT_SOURCE_TABLE,
  WORKER_FIRST_NM,
  WORKER_LAST_NM,
  WORKER_ID,
  WORKER_LAST_UPDATED,  
  CAS_IBMSNAP_LOGMARKER,
  CAS_IBMSNAP_OPERATION,
  CLC_IBMSNAP_LOGMARKER,
  CLC_IBMSNAP_OPERATION,
  CLP_IBMSNAP_LOGMARKER,
  CLP_IBMSNAP_OPERATION,
  STF_IBMSNAP_LOGMARKER,
  STF_IBMSNAP_OPERATION,
  LAST_CHG
) AS
SELECT
  CAS.IDENTIFIER AS CASE_ID,
  CAS.START_DT   AS START_DATE,
  CAS.END_DT     AS END_DATE,
  CAS.GVR_ENTC   AS COUNTY,
  CAS.SRV_CMPC   AS SERVICE_COMP,
  CAS.LMT_ACSSCD AS LIMITED_ACCESS_CODE,
  CAS.LMT_ACS_DT AS LIMITED_ACCESS_DATE,
  CAS.LMT_ACSDSC AS LIMITED_ACCESS_DESCRIPTION,
  CAS.L_GVR_ENTC AS LIMITED_ACCESS_GOVERNMENT_ENT,
  CAS.LST_UPD_TS AS CASE_LAST_UPDATED,
  CLC.COM_FST_NM AS FOCUS_CHLD_FIRST_NM,
  CLC.COM_LST_NM AS FOCUS_CHLD_LAST_NM,
  CLC.IDENTIFIER AS FOCUS_CHILD_ID,
  CLC.SENSTV_IND AS FOCUS_CHILD_SENSITIVITY_IND,
  CLC.LST_UPD_TS AS FOCUS_CHILD_LAST_UPDATED,
  CLP.COM_FST_NM AS PARENT_FIRST_NM,
  CLP.COM_LST_NM AS PARENT_LAST_NM,
  CLR.CLNTRELC   AS PARENT_RELATIONSHIP,
  CLP.IDENTIFIER AS PARENT_ID,
  CLP.SENSTV_IND AS PARENT_SENSITIVITY_IND,
  CLP.LST_UPD_TS AS PARENT_LAST_UPDATED,
  'CLIENT_T'     AS PARENT_SOURCE_TABLE,
  STF.FIRST_NM   AS WORKER_FIRST_NM,
  STF.LAST_NM    AS WORKER_LAST_NM,
  STF.IDENTIFIER AS WORKER_ID,
  STF.LST_UPD_TS AS WORKER_LAST_UPDATED,  
  CAS.IBMSNAP_LOGMARKER AS CAS_IBMSNAP_LOGMARKER,
  CAS.IBMSNAP_OPERATION AS CAS_IBMSNAP_OPERATION,
  CLC.IBMSNAP_LOGMARKER AS CLC_IBMSNAP_LOGMARKER,
  CLC.IBMSNAP_OPERATION AS CLC_IBMSNAP_OPERATION,
  CLP.IBMSNAP_LOGMARKER AS CLP_IBMSNAP_LOGMARKER,
  CLP.IBMSNAP_OPERATION AS CLP_IBMSNAP_OPERATION,
  STF.IBMSNAP_LOGMARKER AS STF_IBMSNAP_LOGMARKER,
  STF.IBMSNAP_OPERATION AS STF_IBMSNAP_OPERATION,
  MAX (
    NVL(CAS.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
    NVL(CLC.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
    NVL(CLP.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40'))    
  ) LAST_CHG
FROM CASE_T CAS
LEFT JOIN CHLD_CLT CCL ON CCL.FKCLIENT_T = CAS.FKCHLD_CLT
LEFT JOIN CLIENT_T CLC ON CLC.IDENTIFIER = CCL.FKCLIENT_T
JOIN CLN_RELT CLR ON CLR.FKCLIENT_0 = CCL.FKCLIENT_T AND ((CLR.CLNTRELC BETWEEN 187 and 214) OR
(CLR.CLNTRELC BETWEEN 245 and 254) OR (CLR.CLNTRELC BETWEEN 282 and 294) OR (CLR.CLNTRELC IN (272, 273, 5620, 6360, 6361)))
JOIN CLIENT_T CLP ON CLP.IDENTIFIER = CLR.FKCLIENT_T
LEFT JOIN STFPERST STF ON STF.IDENTIFIER = CAS.FKSTFPERST
UNION
SELECT
  CAS.IDENTIFIER AS CASE_ID,
  CAS.START_DT   AS START_DATE,
  CAS.END_DT     AS END_DATE,
  CAS.GVR_ENTC   AS COUNTY,
  CAS.SRV_CMPC   AS SERVICE_COMP,
  CAS.LMT_ACSSCD AS LIMITED_ACCESS_CODE,
  CAS.LMT_ACS_DT AS LIMITED_ACCESS_DATE,
  CAS.LMT_ACSDSC AS LIMITED_ACCESS_DESCRIPTION,
  CAS.L_GVR_ENTC AS LIMITED_ACCESS_GOVERNMENT_ENT,
  CAS.LST_UPD_TS AS CASE_LAST_UPDATED,
  CLC.COM_FST_NM AS FOCUS_CHLD_FIRST_NM,
  CLC.COM_LST_NM AS FOCUS_CHLD_LAST_NM,
  CLC.IDENTIFIER AS FOCUS_CHILD_ID,
  CLC.SENSTV_IND AS FOCUS_CHILD_SENSITIVITY_IND,
  CLC.LST_UPD_TS AS FOCUS_CHILD_LAST_UPDATED,
  CLP.COM_FST_NM AS PARENT_FIRST_NM,
  CLP.COM_LST_NM AS PARENT_LAST_NM,
  CLR.CLNTRELC   AS PARENT_RELATIONSHIP,
  CLP.IDENTIFIER AS PARENT_ID,
  CLP.SENSTV_IND AS PARENT_SENSITIVITY_IND,
  CLP.LST_UPD_TS AS PARENT_LAST_UPDATED,
  'CLIENT_T'     AS PARENT_SOURCE_TABLE,
  STF.FIRST_NM   AS WORKER_FIRST_NM,
  STF.LAST_NM    AS WORKER_LAST_NM,
  STF.IDENTIFIER AS WORKER_ID,
  STF.LST_UPD_TS AS WORKER_LAST_UPDATED,  
  CAS.IBMSNAP_LOGMARKER AS CAS_IBMSNAP_LOGMARKER,
  CAS.IBMSNAP_OPERATION AS CAS_IBMSNAP_OPERATION,
  CLC.IBMSNAP_LOGMARKER AS CLC_IBMSNAP_LOGMARKER,
  CLC.IBMSNAP_OPERATION AS CLC_IBMSNAP_OPERATION,
  CLP.IBMSNAP_LOGMARKER AS CLP_IBMSNAP_LOGMARKER,
  CLP.IBMSNAP_OPERATION AS CLP_IBMSNAP_OPERATION,
  STF.IBMSNAP_LOGMARKER AS STF_IBMSNAP_LOGMARKER,
  STF.IBMSNAP_OPERATION AS STF_IBMSNAP_OPERATION,
  MAX (
    NVL(CAS.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
    NVL(CLC.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
    NVL(CLP.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40'))    
  ) LAST_CHG
FROM CASE_T CAS
LEFT JOIN CHLD_CLT CCL ON CCL.FKCLIENT_T = CAS.FKCHLD_CLT
LEFT JOIN CLIENT_T CLC ON CLC.IDENTIFIER = CCL.FKCLIENT_T
JOIN CLN_RELT CLR ON CLR.FKCLIENT_T = CCL.FKCLIENT_T AND ((CLR.CLNTRELC BETWEEN 187 and 214) OR
(CLR.CLNTRELC BETWEEN 245 and 254) OR (CLR.CLNTRELC BETWEEN 282 and 294) OR (CLR.CLNTRELC IN (272, 273, 5620, 6360, 6361)))
JOIN CLIENT_T CLP ON CLP.IDENTIFIER = CLR.FKCLIENT_0
LEFT JOIN STFPERST STF ON STF.IDENTIFIER = CAS.FKSTFPERST;

COMMIT;


CREATE VIEW VW_LST_CLIENT_ADDRESS (
  CLT_IDENTIFIER,
  CLT_LST_UPD_ID,
  CLT_LST_UPD_TS,
  CLT_ADJDEL_IND,
  CLT_ADPTN_STCD,
  CLT_ALN_REG_NO,
  CLT_BIRTH_CITY,
  CLT_B_CNTRY_C,
  CLT_BIRTH_DT,
  CLT_BR_FAC_NM,
  CLT_B_STATE_C,
  CLT_BP_VER_IND,
  CLT_CHLD_CLT_B,
  CLT_CL_INDX_NO,
  CLT_COMMNT_DSC,
  CLT_COM_FST_NM,
  CLT_COM_LST_NM,
  CLT_COM_MID_NM,
  CLT_CONF_ACTDT,
  CLT_CONF_EFIND,
  CLT_CREATN_DT,
  CLT_CURRCA_IND,
  CLT_COTH_DESC,
  CLT_CURREG_IND,
  CLT_DEATH_DT,
  CLT_DTH_DT_IND,
  CLT_DEATH_PLC,
  CLT_DTH_RN_TXT,
  CLT_DRV_LIC_NO,
  CLT_D_STATE_C,
  CLT_EMAIL_ADDR,
  CLT_EST_DOB_CD,
  CLT_ETH_UD_CD,
  CLT_FTERM_DT,
  CLT_GENDER_CD,
  CLT_HEALTH_TXT,
  CLT_HISP_UD_CD,
  CLT_HISP_CD,
  CLT_I_CNTRY_C,
  CLT_IMGT_STC,
  CLT_INCAPC_CD,
  CLT_HCARE_IND,
  CLT_LIMIT_IND,
  CLT_LITRATE_CD,
  CLT_MAR_HIST_B,
  CLT_MRTL_STC,
  CLT_MILT_STACD,
  CLT_MTERM_DT,
  CLT_NMPRFX_DSC,
  CLT_NAME_TPC,
  CLT_OUTWRT_IND,
  CLT_PREVCA_IND,
  CLT_POTH_DESC,
  CLT_PREREG_IND,
  CLT_P_ETHNCTYC,
  CLT_P_LANG_TPC,
  CLT_RLGN_TPC,
  CLT_S_LANG_TC,
  CLT_SNTV_HLIND,
  CLT_SENSTV_IND,
  CLT_SOCPLC_CD,
  CLT_SOC158_IND,
  CLT_SSN_CHG_CD,
  CLT_SS_NO,
  CLT_SUFX_TLDSC,
  CLT_TRBA_CLT_B,
  CLT_TR_MBVRT_B,
  CLT_UNEMPLY_CD,
  CLT_ZIPPY_IND,
  CLT_IBMSNAP_LOGMARKER,
  CLT_IBMSNAP_OPERATION,
  CLA_IDENTIFIER,
  CLA_LST_UPD_ID,
  CLA_LST_UPD_TS,
  CLA_ADDR_TPC,
  CLA_BK_INMT_ID,
  CLA_EFF_END_DT,
  CLA_EFF_STRTDT,
  CLA_FKADDRS_T,
  CLA_FKCLIENT_T,
  CLA_FKREFERL_T,
  CLA_HOMLES_IND,
  CLA_IBMSNAP_LOGMARKER,
  CLA_IBMSNAP_OPERATION,
  ADR_IDENTIFIER,
  ADR_LST_UPD_ID,
  ADR_LST_UPD_TS,
  ADR_ADDR_DSC,
  ADR_CITY_NM,
  ADR_EMRG_EXTNO,
  ADR_EMRG_TELNO,
  ADR_FRG_ADRT_B,
  ADR_GVR_ENTC,
  ADR_HEADER_ADR,
  ADR_MSG_EXT_NO,
  ADR_MSG_TEL_NO,
  ADR_POSTDIR_CD,
  ADR_PREDIR_CD,
  ADR_PRM_EXT_NO,
  ADR_PRM_TEL_NO,
  ADR_STATE_C,
  ADR_STREET_NM,
  ADR_STREET_NO,
  ADR_ST_SFX_C,
  ADR_UNT_DSGC,
  ADR_UNIT_NO,
  ADR_ZIP_NO,
  ADR_ZIP_SFX_NO,
  ADR_IBMSNAP_LOGMARKER,
  ADR_IBMSNAP_OPERATION,
  LAST_CHG
) AS 
SELECT 
clt.IDENTIFIER AS CLT_IDENTIFIER,
clt.LST_UPD_ID AS CLT_LST_UPD_ID,
clt.LST_UPD_TS AS CLT_LST_UPD_TS,
clt.ADJDEL_IND AS CLT_ADJDEL_IND,
clt.ADPTN_STCD AS CLT_ADPTN_STCD,
clt.ALN_REG_NO AS CLT_ALN_REG_NO,
clt.BIRTH_CITY AS CLT_BIRTH_CITY,
clt.B_CNTRY_C  AS CLT_B_CNTRY_C, 
clt.BIRTH_DT   AS CLT_BIRTH_DT,  
clt.BR_FAC_NM  AS CLT_BR_FAC_NM, 
clt.B_STATE_C  AS CLT_B_STATE_C, 
clt.BP_VER_IND AS CLT_BP_VER_IND,
clt.CHLD_CLT_B AS CLT_CHLD_CLT_B,
clt.CL_INDX_NO AS CLT_CL_INDX_NO,
clt.COMMNT_DSC AS CLT_COMMNT_DSC,
clt.COM_FST_NM AS CLT_COM_FST_NM,
clt.COM_LST_NM AS CLT_COM_LST_NM,
clt.COM_MID_NM AS CLT_COM_MID_NM,
clt.CONF_ACTDT AS CLT_CONF_ACTDT,
clt.CONF_EFIND AS CLT_CONF_EFIND,
clt.CREATN_DT  AS CLT_CREATN_DT, 
clt.CURRCA_IND AS CLT_CURRCA_IND,
clt.COTH_DESC  AS CLT_COTH_DESC, 
clt.CURREG_IND AS CLT_CURREG_IND,
clt.DEATH_DT   AS CLT_DEATH_DT,  
clt.DTH_DT_IND AS CLT_DTH_DT_IND,
clt.DEATH_PLC  AS CLT_DEATH_PLC, 
clt.DTH_RN_TXT AS CLT_DTH_RN_TXT,
clt.DRV_LIC_NO AS CLT_DRV_LIC_NO,
clt.D_STATE_C  AS CLT_D_STATE_C, 
clt.EMAIL_ADDR AS CLT_EMAIL_ADDR,
clt.EST_DOB_CD AS CLT_EST_DOB_CD,
clt.ETH_UD_CD  AS CLT_ETH_UD_CD, 
clt.FTERM_DT   AS CLT_FTERM_DT,  
clt.GENDER_CD  AS CLT_GENDER_CD, 
clt.HEALTH_TXT AS CLT_HEALTH_TXT,
clt.HISP_UD_CD AS CLT_HISP_UD_CD,
clt.HISP_CD    AS CLT_HISP_CD,   
clt.I_CNTRY_C  AS CLT_I_CNTRY_C, 
clt.IMGT_STC   AS CLT_IMGT_STC,  
clt.INCAPC_CD  AS CLT_INCAPC_CD, 
clt.HCARE_IND  AS CLT_HCARE_IND, 
clt.LIMIT_IND  AS CLT_LIMIT_IND, 
clt.LITRATE_CD AS CLT_LITRATE_CD,
clt.MAR_HIST_B AS CLT_MAR_HIST_B,
clt.MRTL_STC   AS CLT_MRTL_STC,  
clt.MILT_STACD AS CLT_MILT_STACD,
clt.MTERM_DT   AS CLT_MTERM_DT,  
clt.NMPRFX_DSC AS CLT_NMPRFX_DSC,
clt.NAME_TPC   AS CLT_NAME_TPC,  
clt.OUTWRT_IND AS CLT_OUTWRT_IND,
clt.PREVCA_IND AS CLT_PREVCA_IND,
clt.POTH_DESC  AS CLT_POTH_DESC, 
clt.PREREG_IND AS CLT_PREREG_IND,
clt.P_ETHNCTYC AS CLT_P_ETHNCTYC,
clt.P_LANG_TPC AS CLT_P_LANG_TPC,
clt.RLGN_TPC   AS CLT_RLGN_TPC,  
clt.S_LANG_TC  AS CLT_S_LANG_TC, 
clt.SNTV_HLIND AS CLT_SNTV_HLIND,
clt.SENSTV_IND AS CLT_SENSTV_IND,
clt.SOCPLC_CD  AS CLT_SOCPLC_CD, 
clt.SOC158_IND AS CLT_SOC158_IND,
clt.SSN_CHG_CD AS CLT_SSN_CHG_CD,
clt.SS_NO      AS CLT_SS_NO,    
clt.SUFX_TLDSC AS CLT_SUFX_TLDSC,
clt.TRBA_CLT_B AS CLT_TRBA_CLT_B,
clt.TR_MBVRT_B AS CLT_TR_MBVRT_B,
clt.UNEMPLY_CD AS CLT_UNEMPLY_CD,
clt.ZIPPY_IND  AS CLT_ZIPPY_IND, 
cla.IDENTIFIER AS CLA_IDENTIFIER,
cla.LST_UPD_ID AS CLA_LST_UPD_ID,
cla.LST_UPD_TS AS CLA_LST_UPD_TS,
cla.ADDR_TPC   AS CLA_ADDR_TPC,  
cla.BK_INMT_ID AS CLA_BK_INMT_ID,
cla.EFF_END_DT AS CLA_EFF_END_DT,
cla.EFF_STRTDT AS CLA_EFF_STRTDT,
cla.FKADDRS_T  AS CLA_FKADDRS_T, 
cla.FKCLIENT_T AS CLA_FKCLIENT_T,
cla.FKREFERL_T AS CLA_FKREFERL_T,
cla.HOMLES_IND AS CLA_HOMLES_IND,
adr.IDENTIFIER        AS ADR_IDENTIFIER,
adr.LST_UPD_ID        AS ADR_LST_UPD_ID,
adr.LST_UPD_TS        AS ADR_LST_UPD_TS,
TRIM(adr.ADDR_DSC)    AS ADR_ADDR_DSC,
TRIM(adr.CITY_NM)     AS ADR_CITY_NM,
adr.EMRG_EXTNO        AS ADR_EMRG_EXTNO,
adr.EMRG_TELNO        AS ADR_EMRG_TELNO,
adr.FRG_ADRT_B        AS ADR_FRG_ADRT_B,
adr.GVR_ENTC          AS ADR_GVR_ENTC,  
TRIM(adr.HEADER_ADR)  AS ADR_HEADER_ADR,
adr.MSG_EXT_NO        AS ADR_MSG_EXT_NO,
adr.MSG_TEL_NO        AS ADR_MSG_TEL_NO,
TRIM(adr.POSTDIR_CD)  AS ADR_POSTDIR_CD,
TRIM(adr.PREDIR_CD)   AS ADR_PREDIR_CD,
adr.PRM_EXT_NO        AS ADR_PRM_EXT_NO,
adr.PRM_TEL_NO        AS ADR_PRM_TEL_NO,
adr.STATE_C           AS ADR_STATE_C,   
TRIM(adr.STREET_NM)   AS ADR_STREET_NM,
TRIM(adr.STREET_NO)   AS ADR_STREET_NO,
adr.ST_SFX_C          AS ADR_ST_SFX_C,
adr.UNT_DSGC          AS ADR_UNT_DSGC,
TRIM(adr.UNIT_NO)     AS ADR_UNIT_NO,
TRIM(adr.ZIP_NO)      AS ADR_ZIP_NO,
adr.ZIP_SFX_NO        AS ADR_ZIP_SFX_NO,
adr.IBMSNAP_LOGMARKER AS ADR_IBMSNAP_LOGMARKER,
adr.IBMSNAP_OPERATION AS ADR_IBMSNAP_OPERATION,
clt.IBMSNAP_LOGMARKER AS CLT_IBMSNAP_LOGMARKER,
clt.IBMSNAP_OPERATION AS CLT_IBMSNAP_OPERATION,
cla.IBMSNAP_LOGMARKER AS CLA_IBMSNAP_LOGMARKER,
cla.IBMSNAP_OPERATION AS CLA_IBMSNAP_OPERATION,
MAX(  clt.IBMSNAP_LOGMARKER, 
  NVL(cla.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
  NVL(adr.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40'))
) LAST_CHG
FROM CLIENT_T clt
LEFT JOIN CL_ADDRT cla ON clt.IDENTIFIER = cla.FKCLIENT_T 
LEFT JOIN ADDRS_T  adr ON cla.FKADDRS_T  = adr.IDENTIFIER;

COMMIT;



CREATE VIEW VW_LST_OTHER_CLIENT_NAME (
  THIRD_ID, 
  FIRST_NM, 
  LAST_NM, 
  MIDDLE_NM, 
  NMPRFX_DSC,
  NAME_TPC, 
  SUFX_TLDSC, 
  LST_UPD_ID, 
  LST_UPD_TS, 
  FKCLIENT_T,   
  IBMSNAP_OPERATION, 
  IBMSNAP_LOGMARKER,
  CLIENT_SENSITIVITY_IND,
  LAST_CHG
) AS 
SELECT 
  ONM.THIRD_ID          AS THIRD_ID, 
  ONM.FIRST_NM          AS FIRST_NM, 
  ONM.LAST_NM           AS LAST_NM, 
  ONM.MIDDLE_NM         AS MIDDLE_NM, 
  ONM.NMPRFX_DSC        AS NMPRFX_DSC,
  ONM.NAME_TPC          AS NAME_TPC, 
  ONM.SUFX_TLDSC        AS SUFX_TLDSC, 
  ONM.LST_UPD_ID        AS LST_UPD_ID, 
  ONM.LST_UPD_TS        AS LST_UPD_TS, 
  ONM.FKCLIENT_T        AS FKCLIENT_T,   
  ONM.IBMSNAP_OPERATION AS IBMSNAP_OPERATION, 
  ONM.IBMSNAP_LOGMARKER AS IBMSNAP_LOGMARKER,
  CLT.SENSTV_IND        AS CLIENT_SENSITIVITY_IND,
  MAX(ONM.IBMSNAP_LOGMARKER, CLT.IBMSNAP_LOGMARKER) LAST_CHG
FROM OCL_NM_T ONM
JOIN CLIENT_T CLT ON CLT.IDENTIFIER = ONM.FKCLIENT_T;

COMMIT;


CREATE VIEW VW_LST_PARENT_CASE_HIST AS
SELECT DISTINCT 
    v2.PARENT_ID AS PARENT_PERSON_ID,
	v1.CASE_ID,
	v1.START_DATE,
	v1.END_DATE,
	v1.COUNTY,
	v1.SERVICE_COMP,
	v1.LIMITED_ACCESS_CODE,
	v1.LIMITED_ACCESS_DATE,
	v1.LIMITED_ACCESS_DESCRIPTION,
	v1.LIMITED_ACCESS_GOVERNMENT_ENT,
	v1.CASE_LAST_UPDATED,
	v1.FOCUS_CHLD_FIRST_NM,
	v1.FOCUS_CHLD_LAST_NM,
	v1.FOCUS_CHILD_ID,
	v1.FOCUS_CHILD_SENSITIVITY_IND,
	v1.FOCUS_CHILD_LAST_UPDATED,
	v1.PARENT_FIRST_NM,
	v1.PARENT_LAST_NM,
	v1.PARENT_RELATIONSHIP,
	v1.PARENT_ID,
	v1.PARENT_SENSITIVITY_IND,
	v1.PARENT_LAST_UPDATED,
	v1.PARENT_SOURCE_TABLE,
	v1.WORKER_FIRST_NM,
	v1.WORKER_LAST_NM,
	v1.WORKER_ID,
	v1.WORKER_LAST_UPDATED,
	v1.CAS_IBMSNAP_LOGMARKER,
	v1.CAS_IBMSNAP_OPERATION,
	v1.CLC_IBMSNAP_LOGMARKER,
	v1.CLC_IBMSNAP_OPERATION,
	v1.CLP_IBMSNAP_LOGMARKER,
	v1.CLP_IBMSNAP_OPERATION,
	v1.STF_IBMSNAP_LOGMARKER,
	v1.STF_IBMSNAP_OPERATION,
	v1.LAST_CHG
FROM VW_LST_CASE_HIST v1 
JOIN VW_LST_CASE_HIST v2 ON v1.CASE_ID = v2.CASE_ID;

COMMIT;


CREATE VIEW VW_LST_REFERRAL_HIST (
  CLIENT_ID,
  CLIENT_SENSITIVITY_IND,
  REFERRAL_ID,
  START_DATE,
  END_DATE,
  REFERRAL_RESPONSE_TYPE,
  LIMITED_ACCESS_CODE,
  LIMITED_ACCESS_DATE,
  LIMITED_ACCESS_DESCRIPTION,
  LIMITED_ACCESS_GOVERNMENT_ENT,
  REFERRAL_LAST_UPDATED,
  REPORTER_ID,
  REPORTER_FIRST_NM,
  REPORTER_LAST_NM,
  REPORTER_LAST_UPDATED,
  WORKER_ID,
  WORKER_FIRST_NM,
  WORKER_LAST_NM,
  WORKER_LAST_UPDATED,
  PERPETRATOR_ID,
  PERPETRATOR_SENSITIVITY_IND,
  PERPETRATOR_FIRST_NM,
  PERPETRATOR_LAST_NM,
  PERPETRATOR_LAST_UPDATED,
  VICTIM_ID,
  VICTIM_SENSITIVITY_IND,
  VICTIM_FIRST_NM,
  VICTIM_LAST_NM,
  VICTIM_LAST_UPDATED,
  REFERRAL_COUNTY,
  ALLEGATION_ID,
  ALLEGATION_DISPOSITION,
  ALLEGATION_TYPE,
  ALLEGATION_LAST_UPDATED,
  RCT_IBMSNAP_LOGMARKER,
  RCT_IBMSNAP_OPERATION,
  RFL_IBMSNAP_LOGMARKER,
  RFL_IBMSNAP_OPERATION,
  STP_IBMSNAP_LOGMARKER,
  STP_IBMSNAP_OPERATION,
  RPT_IBMSNAP_LOGMARKER,
  RPT_IBMSNAP_OPERATION,
  ALG_IBMSNAP_LOGMARKER,
  ALG_IBMSNAP_OPERATION,
  CLP_IBMSNAP_LOGMARKER,
  CLP_IBMSNAP_OPERATION,
  CLV_IBMSNAP_LOGMARKER,
  CLV_IBMSNAP_OPERATION,
  LAST_CHG
) AS
SELECT
  CLT.IDENTIFIER AS CLIENT_ID,
  CLT.SENSTV_IND AS CLIENT_SENSITIVITY_IND,
  RFL.IDENTIFIER AS REFERRAL_ID,
  RFL.REF_RCV_DT AS START_DATE,
  RFL.REFCLSR_DT AS END_DATE,
  RFL.RFR_RSPC   AS REFERRAL_RESPONSE_TYPE,
  RFL.LMT_ACSSCD AS LIMITED_ACCESS_CODE,
  RFL.LMT_ACS_DT AS LIMITED_ACCESS_DATE,
  RFL.LMT_ACSDSC AS LIMITED_ACCESS_DESCRIPTION,
  RFL.L_GVR_ENTC AS LIMITED_ACCESS_GOVERNMENT_ENT,
  RFL.LST_UPD_TS AS REFERRAL_LAST_UPDATED,
  RPT.FKREFERL_T AS REPORTER_ID,
  RPT.RPTR_FSTNM AS REPORTER_FIRST_NM,
  RPT.RPTR_LSTNM AS REPORTER_LAST_NM,
  RPT.LST_UPD_TS AS REPORTER_LAST_UPDATED,
  STP.IDENTIFIER AS WORKER_ID,
  STP.FIRST_NM   AS WORKER_FIRST_NM,
  STP.LAST_NM    AS WORKER_LAST_NM,
  STP.LST_UPD_TS AS WORKER_LAST_UPDATED,
  CLP.IDENTIFIER AS PERPETRATOR_ID,
  CLP.SENSTV_IND AS PERPETRATOR_SENSITIVITY_IND,
  CLP.COM_FST_NM AS PERPETRATOR_FIRST_NM,
  CLP.COM_LST_NM AS PERPETRATOR_LAST_NM,
  CLP.LST_UPD_TS AS PERPETRATOR_LAST_UPDATED,
  CLV.IDENTIFIER AS VICTIM_ID,
  CLV.SENSTV_IND AS VICTIM_SENSITIVITY_IND,
  CLV.COM_FST_NM AS VICTIM_FIRST_NM,
  CLV.COM_LST_NM AS VICTIM_LAST_NM,
  CLV.LST_UPD_TS AS VICTIM_LAST_UPDATED,
  RFL.GVR_ENTC   AS REFERRAL_COUNTY,
  ALG.IDENTIFIER AS ALLEGATION_ID,
  ALG.ALG_DSPC   AS ALLEGATION_DISPOSITION,
  ALG.ALG_TPC    AS ALLEGATION_TYPE,
  ALG.LST_UPD_TS AS ALLEGATION_LAST_UPDATED,
  RCT.IBMSNAP_LOGMARKER AS RCT_IBMSNAP_LOGMARKER,
  RCT.IBMSNAP_OPERATION AS RCT_IBMSNAP_OPERATION,
  RFL.IBMSNAP_LOGMARKER AS RFL_IBMSNAP_LOGMARKER,
  RFL.IBMSNAP_OPERATION AS RFL_IBMSNAP_OPERATION,
  STP.IBMSNAP_LOGMARKER AS STP_IBMSNAP_LOGMARKER,
  STP.IBMSNAP_OPERATION AS STP_IBMSNAP_OPERATION,
  RPT.IBMSNAP_LOGMARKER AS RPT_IBMSNAP_LOGMARKER,
  RPT.IBMSNAP_OPERATION AS RPT_IBMSNAP_OPERATION,
  ALG.IBMSNAP_LOGMARKER AS ALG_IBMSNAP_LOGMARKER,
  ALG.IBMSNAP_OPERATION AS ALG_IBMSNAP_OPERATION,
  CLP.IBMSNAP_LOGMARKER AS CLP_IBMSNAP_LOGMARKER,
  CLP.IBMSNAP_OPERATION AS CLP_IBMSNAP_OPERATION,
  CLV.IBMSNAP_LOGMARKER AS CLV_IBMSNAP_LOGMARKER,
  CLV.IBMSNAP_OPERATION AS CLV_IBMSNAP_OPERATION,
  MAX ( CLT.IBMSNAP_LOGMARKER,
    NVL(RCT.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
    NVL(RFL.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
    NVL(STP.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
    NVL(RPT.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
    NVL(ALG.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
    NVL(CLP.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40')),
    NVL(CLV.IBMSNAP_LOGMARKER, TIMESTAMP('2008-09-30 11:54:40'))
  ) AS LAST_CHG
FROM REFR_CLT      RCT
JOIN CLIENT_T      CLT ON CLT.IDENTIFIER  = RCT.FKCLIENT_T
LEFT JOIN REFERL_T RFL ON RCT.FKREFERL_T  = RFL.IDENTIFIER
LEFT JOIN STFPERST STP ON RFL.FKSTFPERST  = STP.IDENTIFIER
LEFT JOIN REPTR_T  RPT ON RPT.FKREFERL_T  = RFL.IDENTIFIER
LEFT JOIN ALLGTN_T ALG ON ALG.FKREFERL_T  = RFL.IDENTIFIER
LEFT JOIN CLIENT_T CLP ON CLP.IDENTIFIER  = ALG.FKCLIENT_0
LEFT JOIN CLIENT_T CLV ON CLV.IDENTIFIER  = ALG.FKCLIENT_T
WHERE RCT.FKREFERL_T IN (
	SELECT GT.IDENTIFIER FROM GT_ID GT
);

COMMIT;



CREATE VIEW VW_MQT_BI_DIR_RELATION (
 REVERSE_RELATIONSHIP,
 THIS_LEGACY_ID,
 THIS_SENSITIVITY_IND,
 THIS_LEGACY_LAST_UPDATED,
 THIS_LEGACY_LAST_UPDATED_ID,
 THIS_FIRST_NAME,
 THIS_LAST_NAME,
 REL_CODE,
 RELATED_LEGACY_ID,
 RELATED_SENSITIVITY_IND,
 RELATED_LEGACY_LAST_UPDATED,
 RELATED_LEGACY_LAST_UPDATED_ID,
 RELATED_FIRST_NAME,
 RELATED_LAST_NAME,
 THIS_IBMSNAP_LOGMARKER,
 THIS_IBMSNAP_OPERATION,
 RELATED_IBMSNAP_LOGMARKER,
 RELATED_IBMSNAP_OPERATION,
 LAST_CHG
) AS
SELECT
 0 AS REVERSE_RELATIONSHIP,
 v.THIS_LEGACY_ID,
 v.THIS_SENSITIVITY_IND,
 v.THIS_LEGACY_LAST_UPDATED,
 v.THIS_LEGACY_LAST_UPDATED_ID,
 v.THIS_FIRST_NAME,
 v.THIS_LAST_NAME,
 v.REL_CODE,
 v.RELATED_LEGACY_ID,
 v.RELATED_SENSITIVITY_IND,
 v.RELATED_LEGACY_LAST_UPDATED,
 v.RELATED_LEGACY_LAST_UPDATED_ID,
 v.RELATED_FIRST_NAME,
 v.RELATED_LAST_NAME,
 v.THIS_IBMSNAP_LOGMARKER,
 v.THIS_IBMSNAP_OPERATION,
 v.RELATED_IBMSNAP_LOGMARKER,
 v.RELATED_IBMSNAP_OPERATION,
 v.LAST_CHG
FROM MQT_REL_CLN_RELT_CLIENT v
UNION ALL
SELECT
 1 AS REVERSE_RELATIONSHIP,
 v.RELATED_LEGACY_ID,
 v.RELATED_SENSITIVITY_IND,
 v.RELATED_LEGACY_LAST_UPDATED,
 v.RELATED_LEGACY_LAST_UPDATED_ID,
 v.RELATED_FIRST_NAME,
 v.RELATED_LAST_NAME,
 v.REL_CODE,
 v.THIS_LEGACY_ID,
 v.THIS_SENSITIVITY_IND,
 v.THIS_LEGACY_LAST_UPDATED,
 v.THIS_LEGACY_LAST_UPDATED_ID,
 v.THIS_FIRST_NAME,
 v.THIS_LAST_NAME,
 v.THIS_IBMSNAP_LOGMARKER,
 v.THIS_IBMSNAP_OPERATION,
 v.RELATED_IBMSNAP_LOGMARKER,
 v.RELATED_IBMSNAP_OPERATION,
 v.LAST_CHG
FROM MQT_REL_CLN_RELT_CLIENT v;

COMMIT;


CREATE VIEW VW_MQT_PARENT_CASE_HIST AS
SELECT DISTINCT v2.PARENT_ID AS PARENT_PERSON_ID, v1.* 
FROM MQT_CASE_HIST v1 
JOIN MQT_CASE_HIST v2 ON v1.CASE_ID = v2.CASE_ID;

COMMIT;




GRANT ALL PRIVILEGES ON GT_ID TO CWDSPEF;

COMMIT;

GRANT ALL PRIVILEGES ON GT_REFR_CLT TO CWDSPEF;

COMMIT;


GRANT SELECT ON MQT_CASE_HIST TO CWDPEF;

COMMIT;

GRANT SELECT ON MQT_CLIENT_ADDRESS TO CWDPEF;

COMMIT;

GRANT SELECT ON MQT_OTHER_CLIENT_NAME TO CWDPEF;

COMMIT;

GRANT SELECT ON MQT_REL_CLN_RELT_CLIENT TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_BI_DIR_RELATION TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_CASE_HIST TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_CLIENT_ADDRESS TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_OTHER_CLIENT_NAME TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_PARENT_CASE_HIST TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_REFERRAL_HIST TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_REL_CLN_RELT_CLIENT TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_MQT_BI_DIR_RELATION TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_MQT_PARENT_CASE_HIST TO CWDPEF;

COMMIT;
