SET CURRENT SCHEMA = 'CWSRSQ' ;

GRANT ALL PRIVILEGES ON GT_ID TO CWDSPEF;

COMMIT;

GRANT ALL PRIVILEGES ON GT_REFR_CLT TO CWDSPEF;

COMMIT;


GRANT SELECT ON MQT_CASE_HIST TO CWDPEF;

COMMIT;

GRANT SELECT ON MQT_CLIENT_ADDRESS TO CWDPEF;

COMMIT;

GRANT SELECT ON MQT_OTHER_CLIENT_NAME TO CWDPEF;

COMMIT;

GRANT SELECT ON MQT_REL_CLN_RELT_CLIENT TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_BI_DIR_RELATION TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_CASE_HIST TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_CLIENT_ADDRESS TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_OTHER_CLIENT_NAME TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_PARENT_CASE_HIST TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_REFERRAL_HIST TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_LST_REL_CLN_RELT_CLIENT TO CWDPEF;

COMMIT;

--GRANT SELECT ON VW_LST_SAFETY_ALERT TO CWDPEF;

--COMMIT;

GRANT SELECT ON VW_MQT_BI_DIR_RELATION TO CWDPEF;

COMMIT;

GRANT SELECT ON VW_MQT_PARENT_CASE_HIST TO CWDPEF;

COMMIT;
