SET CURRENT SCHEMA = 'CWSRS1';

GRANT ALL PRIVILEGES ON GT_ID TO CWDSNS1;
GRANT ALL PRIVILEGES ON GT_ID TO CWDSNS2;
GRANT ALL PRIVILEGES ON GT_ID TO CWDSNS3;
GRANT ALL PRIVILEGES ON GT_ID TO CWDSNS4;
GRANT ALL PRIVILEGES ON GT_ID TO CWDSNS5;

COMMIT;


GRANT ALL PRIVILEGES ON GT_REFR_CLT TO CWDSNS1;
GRANT ALL PRIVILEGES ON GT_REFR_CLT TO CWDSNS2;
GRANT ALL PRIVILEGES ON GT_REFR_CLT TO CWDSNS3;
GRANT ALL PRIVILEGES ON GT_REFR_CLT TO CWDSNS4;
GRANT ALL PRIVILEGES ON GT_REFR_CLT TO CWDSNS5;

COMMIT;


GRANT SELECT ON MQT_CASE_HIST TO CWDSNS1;
GRANT SELECT ON MQT_CASE_HIST TO CWDSNS2;
GRANT SELECT ON MQT_CASE_HIST TO CWDSNS3;
GRANT SELECT ON MQT_CASE_HIST TO CWDSNS4;
GRANT SELECT ON MQT_CASE_HIST TO CWDSNS5;

COMMIT;


GRANT SELECT ON MQT_CLIENT_ADDRESS TO CWDSNS1;
GRANT SELECT ON MQT_CLIENT_ADDRESS TO CWDSNS2;
GRANT SELECT ON MQT_CLIENT_ADDRESS TO CWDSNS3;
GRANT SELECT ON MQT_CLIENT_ADDRESS TO CWDSNS4;
GRANT SELECT ON MQT_CLIENT_ADDRESS TO CWDSNS5;

COMMIT;


GRANT SELECT ON MQT_OTHER_CLIENT_NAME TO CWDSNS1;
GRANT SELECT ON MQT_OTHER_CLIENT_NAME TO CWDSNS2;
GRANT SELECT ON MQT_OTHER_CLIENT_NAME TO CWDSNS3;
GRANT SELECT ON MQT_OTHER_CLIENT_NAME TO CWDSNS4;
GRANT SELECT ON MQT_OTHER_CLIENT_NAME TO CWDSNS5;

COMMIT;


GRANT SELECT ON MQT_REL_CLN_RELT_CLIENT TO CWDSNS1;
GRANT SELECT ON MQT_REL_CLN_RELT_CLIENT TO CWDSNS2;
GRANT SELECT ON MQT_REL_CLN_RELT_CLIENT TO CWDSNS3;
GRANT SELECT ON MQT_REL_CLN_RELT_CLIENT TO CWDSNS4;
GRANT SELECT ON MQT_REL_CLN_RELT_CLIENT TO CWDSNS5;

COMMIT;


GRANT SELECT ON VW_LST_BI_DIR_RELATION TO CWDSNS1;
GRANT SELECT ON VW_LST_BI_DIR_RELATION TO CWDSNS2;
GRANT SELECT ON VW_LST_BI_DIR_RELATION TO CWDSNS3;
GRANT SELECT ON VW_LST_BI_DIR_RELATION TO CWDSNS4;
GRANT SELECT ON VW_LST_BI_DIR_RELATION TO CWDSNS5;

COMMIT;


GRANT SELECT ON VW_LST_CASE_HIST TO CWDSNS1;
GRANT SELECT ON VW_LST_CASE_HIST TO CWDSNS2;
GRANT SELECT ON VW_LST_CASE_HIST TO CWDSNS3;
GRANT SELECT ON VW_LST_CASE_HIST TO CWDSNS4;
GRANT SELECT ON VW_LST_CASE_HIST TO CWDSNS5;

COMMIT;


GRANT SELECT ON VW_LST_CLIENT_ADDRESS TO CWDSNS1;
GRANT SELECT ON VW_LST_CLIENT_ADDRESS TO CWDSNS2;
GRANT SELECT ON VW_LST_CLIENT_ADDRESS TO CWDSNS3;
GRANT SELECT ON VW_LST_CLIENT_ADDRESS TO CWDSNS4;
GRANT SELECT ON VW_LST_CLIENT_ADDRESS TO CWDSNS5;

COMMIT;


GRANT SELECT ON VW_LST_OTHER_CLIENT_NAME TO CWDSNS1;
GRANT SELECT ON VW_LST_OTHER_CLIENT_NAME TO CWDSNS2;
GRANT SELECT ON VW_LST_OTHER_CLIENT_NAME TO CWDSNS3;
GRANT SELECT ON VW_LST_OTHER_CLIENT_NAME TO CWDSNS4;
GRANT SELECT ON VW_LST_OTHER_CLIENT_NAME TO CWDSNS5;

COMMIT;


GRANT SELECT ON VW_LST_PARENT_CASE_HIST TO CWDSNS1;
GRANT SELECT ON VW_LST_PARENT_CASE_HIST TO CWDSNS2;
GRANT SELECT ON VW_LST_PARENT_CASE_HIST TO CWDSNS3;
GRANT SELECT ON VW_LST_PARENT_CASE_HIST TO CWDSNS4;
GRANT SELECT ON VW_LST_PARENT_CASE_HIST TO CWDSNS5;

COMMIT;


GRANT SELECT ON VW_LST_REFERRAL_HIST TO CWDSNS1;
GRANT SELECT ON VW_LST_REFERRAL_HIST TO CWDSNS2;
GRANT SELECT ON VW_LST_REFERRAL_HIST TO CWDSNS3;
GRANT SELECT ON VW_LST_REFERRAL_HIST TO CWDSNS4;
GRANT SELECT ON VW_LST_REFERRAL_HIST TO CWDSNS5;

COMMIT;


GRANT SELECT ON VW_LST_REL_CLN_RELT_CLIENT TO CWDSNS1;
GRANT SELECT ON VW_LST_REL_CLN_RELT_CLIENT TO CWDSNS2;
GRANT SELECT ON VW_LST_REL_CLN_RELT_CLIENT TO CWDSNS3;
GRANT SELECT ON VW_LST_REL_CLN_RELT_CLIENT TO CWDSNS4;
GRANT SELECT ON VW_LST_REL_CLN_RELT_CLIENT TO CWDSNS5;

COMMIT;


GRANT SELECT ON VW_LST_SAFETY_ALERT TO CWDSNS1;
GRANT SELECT ON VW_LST_SAFETY_ALERT TO CWDSNS2;
GRANT SELECT ON VW_LST_SAFETY_ALERT TO CWDSNS3;
GRANT SELECT ON VW_LST_SAFETY_ALERT TO CWDSNS4;
GRANT SELECT ON VW_LST_SAFETY_ALERT TO CWDSNS5;

COMMIT;


GRANT SELECT ON VW_MQT_BI_DIR_RELATION TO CWDSNS1;
GRANT SELECT ON VW_MQT_BI_DIR_RELATION TO CWDSNS2;
GRANT SELECT ON VW_MQT_BI_DIR_RELATION TO CWDSNS3;
GRANT SELECT ON VW_MQT_BI_DIR_RELATION TO CWDSNS4;
GRANT SELECT ON VW_MQT_BI_DIR_RELATION TO CWDSNS5;

COMMIT;


GRANT SELECT ON VW_MQT_PARENT_CASE_HIST TO CWDSNS1;
GRANT SELECT ON VW_MQT_PARENT_CASE_HIST TO CWDSNS2;
GRANT SELECT ON VW_MQT_PARENT_CASE_HIST TO CWDSNS3;
GRANT SELECT ON VW_MQT_PARENT_CASE_HIST TO CWDSNS4;
GRANT SELECT ON VW_MQT_PARENT_CASE_HIST TO CWDSNS5;

COMMIT;
