-- SET CURRENT SCHEMA = 'CWSRS1';

DROP VIEW VW_LST_OTHER_CLIENT_NAME;

CREATE VIEW VW_LST_OTHER_CLIENT_NAME (
  THIRD_ID, 
  FIRST_NM, 
  LAST_NM, 
  MIDDLE_NM, 
  NMPRFX_DSC,
  NAME_TPC, 
  SUFX_TLDSC, 
  LST_UPD_ID, 
  LST_UPD_TS, 
  FKCLIENT_T,   
  CLIENT_SENSITIVITY_IND,
  IBMSNAP_OPERATION, 
  IBMSNAP_LOGMARKER,
  LAST_CHG
) AS 
SELECT 
  ONM.THIRD_ID   AS THIRD_ID, 
  ONM.FIRST_NM   AS FIRST_NM, 
  ONM.LAST_NM    AS LAST_NM, 
  ONM.MIDDLE_NM  AS MIDDLE_NM, 
  ONM.NMPRFX_DSC AS NMPRFX_DSC,
  ONM.NAME_TPC   AS NAME_TPC, 
  ONM.SUFX_TLDSC AS SUFX_TLDSC, 
  ONM.LST_UPD_ID AS LST_UPD_ID, 
  ONM.LST_UPD_TS AS LST_UPD_TS, 
  ONM.FKCLIENT_T AS FKCLIENT_T,   
  CLT.SENSTV_IND AS CLIENT_SENSITIVITY_IND,
  ONM.IBMSNAP_OPERATION AS IBMSNAP_OPERATION, 
  ONM.IBMSNAP_LOGMARKER AS IBMSNAP_LOGMARKER,
  MAX(ONM.IBMSNAP_LOGMARKER, CLT.IBMSNAP_LOGMARKER) LAST_CHG
FROM OCL_NM_T ONM
JOIN CLIENT_T CLT ON CLT.IDENTIFIER = ONM.FKCLIENT_T
WHERE CLT.IDENTIFIER IN (
	SELECT GT.IDENTIFIER FROM GT_ID GT
);

COMMIT;
