DROP TRIGGER CWSINT.trg_addrs_upd;

CREATE TRIGGER CWSINT.trg_addrs_upd
AFTER UPDATE ON CWSINT.ADDRS_T
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
UPDATE CWSRS1.ADDRS_T SET 
    CITY_NM = nrow.CITY_NM,
	EMRG_TELNO = nrow.EMRG_TELNO,
	EMRG_EXTNO = nrow.EMRG_EXTNO,
	FRG_ADRT_B = nrow.FRG_ADRT_B,
	GVR_ENTC = nrow.GVR_ENTC,
	MSG_TEL_NO = nrow.MSG_TEL_NO,
	MSG_EXT_NO = nrow.MSG_EXT_NO,
	HEADER_ADR = nrow.HEADER_ADR,
	PRM_TEL_NO = nrow.PRM_TEL_NO,
	PRM_EXT_NO = nrow.PRM_EXT_NO,
	STATE_C = nrow.STATE_C,
	STREET_NM = nrow.STREET_NM,
	STREET_NO = nrow.STREET_NO,
	ZIP_NO = nrow.ZIP_NO,
	LST_UPD_ID = nrow.LST_UPD_ID,
	LST_UPD_TS = nrow.LST_UPD_TS,
	ADDR_DSC = nrow.ADDR_DSC,
	ZIP_SFX_NO = nrow.ZIP_SFX_NO,
	POSTDIR_CD = nrow.POSTDIR_CD,
	PREDIR_CD = nrow.PREDIR_CD,
	ST_SFX_C = nrow.ST_SFX_C,
	UNT_DSGC = nrow.UNT_DSGC,
	UNIT_NO = nrow.UNIT_NO,
	IBMSNAP_OPERATION = 'U',
	IBMSNAP_LOGMARKER = current timestamp
WHERE IDENTIFIER = nrow.identifier;
END
