DROP TRIGGER CWSINT.trg_allgtn_upd;

CREATE TRIGGER CWSINT.trg_allgtn_upd
AFTER UPDATE ON CWSINT.ALLGTN_T
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
UPDATE CWSRS1.ALLGTN_T
SET 
	ABUSE_ENDT = nrow.ABUSE_ENDT,
	ABUSE_FREQ = nrow.ABUSE_FREQ,
	ABUSE_PDCD = nrow.ABUSE_PDCD,
	LOC_DSC = nrow.LOC_DSC,
	ABUSE_STDT = nrow.ABUSE_STDT,
	ALG_DSPC = nrow.ALG_DSPC,
	ALG_TPC = nrow.ALG_TPC,
	DISPSN_DSC = nrow.DISPSN_DSC,
	DISPSN_DT = nrow.DISPSN_DT,
	IJHM_DET_B = nrow.IJHM_DET_B,
	NON_PRT_CD = nrow.NON_PRT_CD,
	STFADD_IND = nrow.STFADD_IND,
	LST_UPD_ID = nrow.LST_UPD_ID,
	LST_UPD_TS = nrow.LST_UPD_TS,
	FKCLIENT_T = nrow.FKCLIENT_T,
	FKCLIENT_0 = nrow.FKCLIENT_0,
	FKREFERL_T = nrow.FKREFERL_T,
	CNTY_SPFCD = nrow.CNTY_SPFCD,
	ZIPPY_IND = nrow.ZIPPY_IND,
	PLC_FCLC = nrow.PLC_FCLC,
	IBMSNAP_OPERATION = 'U',
	IBMSNAP_LOGMARKER = current timestamp
WHERE IDENTIFIER = nrow.identifier;
END
