DROP TRIGGER CWSINT.trg_claddr_del;

CREATE TRIGGER CWSINT.trg_claddr_del
AFTER DELETE ON CWSINT.CL_ADDRT
REFERENCING OLD AS OROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	MERGE INTO CWSRS1.CL_ADDRT cla USING (
		SELECT orow.IDENTIFIER,
			orow.ADDR_TPC,
			orow.BK_INMT_ID,
			orow.EFF_END_DT,
			orow.EFF_STRTDT,
			orow.LST_UPD_ID,
			orow.LST_UPD_TS,
			orow.FKADDRS_T,
			orow.FKCLIENT_T,
			orow.HOMLES_IND,
			orow.FKREFERL_T
		FROM sysibm.sysdummy1
	) X ON (cla.IDENTIFIER = X.IDENTIFIER) 
	WHEN MATCHED THEN UPDATE SET 
	    ADDR_TPC = x.ADDR_TPC,
		BK_INMT_ID = x.BK_INMT_ID,
		EFF_END_DT = x.EFF_END_DT,
		EFF_STRTDT = x.EFF_STRTDT,
		LST_UPD_ID = x.LST_UPD_ID,
		LST_UPD_TS = x.LST_UPD_TS,
		FKADDRS_T = x.FKADDRS_T,
		FKCLIENT_T = x.FKCLIENT_T,
		HOMLES_IND = x.HOMLES_IND,
		FKREFERL_T = x.FKREFERL_T,
		IBMSNAP_OPERATION = 'D',
		IBMSNAP_LOGMARKER = current timestamp
	WHEN NOT MATCHED THEN INSERT(
	    IDENTIFIER,
		ADDR_TPC,
		BK_INMT_ID,
		EFF_END_DT,
		EFF_STRTDT,
		LST_UPD_ID,
		LST_UPD_TS,
		FKADDRS_T,
		FKCLIENT_T,
		HOMLES_IND,
		FKREFERL_T,
		IBMSNAP_OPERATION,
		IBMSNAP_LOGMARKER)
	VALUES(x.IDENTIFIER,
		x.ADDR_TPC,
		x.BK_INMT_ID,
		x.EFF_END_DT,
		x.EFF_STRTDT,
		x.LST_UPD_ID,
		x.LST_UPD_TS,
		x.FKADDRS_T,
		x.FKCLIENT_T,
		x.HOMLES_IND,
		x.FKREFERL_T,
		'D',
		current timestamp);
END
