DROP TRIGGER CWSINT.trg_oth_adlt_upd;

CREATE TRIGGER CWSINT.trg_oth_adlt_upd
AFTER UPDATE ON CWSINT.OTH_ADLT
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	UPDATE CWSRS1.OTH_ADLT SET 
		BIRTH_DT = nrow.BIRTH_DT,
		END_DT = nrow.END_DT,
		GENDER_CD = nrow.GENDER_CD,
		OTH_ADLTNM = nrow.OTH_ADLTNM,
		START_DT = nrow.START_DT,
		LST_UPD_ID = nrow.LST_UPD_ID,
		LST_UPD_TS = nrow.LST_UPD_TS,
		FKPLC_HM_T = nrow.FKPLC_HM_T,
		COMNT_DSC = nrow.COMNT_DSC,
		OTH_ADL_CD = nrow.OTH_ADL_CD,
		IDENTFD_DT = nrow.IDENTFD_DT,
		RESOST_IND = nrow.RESOST_IND,
		PASSBC_CD = nrow.PASSBC_CD,
		IBMSNAP_OPERATION = 'U',
		IBMSNAP_LOGMARKER = current timestamp
	WHERE IDENTIFIER = nrow.identifier;
END
