DROP TRIGGER CWSINT.trg_refr_clt_upd;

CREATE TRIGGER CWSINT.trg_refr_clt_upd
AFTER UPDATE ON CWSINT.REFR_CLT
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	UPDATE CWSRS1.REFR_CLT SET 
		APRVL_NO = nrow.APRVL_NO,
		APV_STC = nrow.APV_STC,
		DSP_RSNC = nrow.DSP_RSNC,
		DISPSTN_CD = nrow.DISPSTN_CD,
		RCL_DISPDT = nrow.RCL_DISPDT,
		SLFRPT_IND = nrow.SLFRPT_IND,
		STFADD_IND = nrow.STFADD_IND,
		LST_UPD_ID = nrow.LST_UPD_ID,
		LST_UPD_TS = nrow.LST_UPD_TS,
		DSP_CLSDSC = nrow.DSP_CLSDSC,
		RFCL_AGENO = nrow.RFCL_AGENO,
		AGE_PRD_CD = nrow.AGE_PRD_CD,
		CNTY_SPFCD = nrow.CNTY_SPFCD,
		MHLTH_IND = nrow.MHLTH_IND,
		ALCHL_IND = nrow.ALCHL_IND,
		DRUG_IND = nrow.DRUG_IND,
		IBMSNAP_OPERATION = 'U',
		IBMSNAP_LOGMARKER = current timestamp
	WHERE FKCLIENT_T = nrow.FKCLIENT_T AND FKREFERL_T = nrow.FKREFERL_T;
END
