DROP TRIGGER CWSINT.trg_refr_clt_del;

CREATE TRIGGER CWSINT.trg_refr_clt_del
AFTER DELETE ON CWSINT.REFR_CLT
REFERENCING OLD AS OROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	MERGE INTO CWSRS1.REFR_CLT tgt USING ( 
		SELECT
			orow.APRVL_NO,
			orow.APV_STC,
			orow.DSP_RSNC,
			orow.DISPSTN_CD,
			orow.RCL_DISPDT,
			orow.SLFRPT_IND,
			orow.STFADD_IND,
			orow.LST_UPD_ID,
			orow.LST_UPD_TS,
			orow.FKCLIENT_T,
			orow.FKREFERL_T,
			orow.DSP_CLSDSC,
			orow.RFCL_AGENO,
			orow.AGE_PRD_CD,
			orow.CNTY_SPFCD,
			orow.MHLTH_IND,
			orow.ALCHL_IND,
			orow.DRUG_IND
		FROM sysibm.sysdummy1
	) X ON (tgt.FKCLIENT_T = X.FKCLIENT_T AND tgt.FKREFERL_T = X.FKREFERL_T)
	WHEN MATCHED THEN UPDATE SET 
		APRVL_NO = x.APRVL_NO,
		APV_STC = x.APV_STC,
		DSP_RSNC = x.DSP_RSNC,
		DISPSTN_CD = x.DISPSTN_CD,
		RCL_DISPDT = x.RCL_DISPDT,
		SLFRPT_IND = x.SLFRPT_IND,
		STFADD_IND = x.STFADD_IND,
		LST_UPD_ID = x.LST_UPD_ID,
		LST_UPD_TS = x.LST_UPD_TS,
		DSP_CLSDSC = x.DSP_CLSDSC,
		RFCL_AGENO = x.RFCL_AGENO,
		AGE_PRD_CD = x.AGE_PRD_CD,
		CNTY_SPFCD = x.CNTY_SPFCD,
		MHLTH_IND = x.MHLTH_IND,
		ALCHL_IND = x.ALCHL_IND,
		DRUG_IND = x.DRUG_IND,
		IBMSNAP_OPERATION = 'D',
		IBMSNAP_LOGMARKER = current timestamp
	WHEN NOT MATCHED THEN INSERT (
		APRVL_NO,
		APV_STC,
		DSP_RSNC,
		DISPSTN_CD,
		RCL_DISPDT,
		SLFRPT_IND,
		STFADD_IND,
		LST_UPD_ID,
		LST_UPD_TS,
		FKCLIENT_T,
		FKREFERL_T,
		DSP_CLSDSC,
		RFCL_AGENO,
		AGE_PRD_CD,
		CNTY_SPFCD,
		MHLTH_IND,
		ALCHL_IND,
		DRUG_IND,
		IBMSNAP_OPERATION,
		IBMSNAP_LOGMARKER
	) VALUES (
		x.APRVL_NO,
		x.APV_STC,
		x.DSP_RSNC,
		x.DISPSTN_CD,
		x.RCL_DISPDT,
		x.SLFRPT_IND,
		x.STFADD_IND,
		x.LST_UPD_ID,
		x.LST_UPD_TS,
		x.FKCLIENT_T,
		x.FKREFERL_T,
		x.DSP_CLSDSC,
		x.RFCL_AGENO,
		x.AGE_PRD_CD,
		x.CNTY_SPFCD,
		x.MHLTH_IND,
		x.ALCHL_IND,
		x.DRUG_IND,
		'D',
		current timestamp
	);
END
