DROP TRIGGER CWSINT.trg_stfperst_upd;

CREATE TRIGGER CWSINT.trg_stfperst_upd
AFTER UPDATE ON CWSINT.STFPERST
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	UPDATE CWSRS1.STFPERST SET 
		END_DT = nrow.END_DT,
		FIRST_NM = nrow.FIRST_NM,
		JOB_TL_DSC = nrow.JOB_TL_DSC,
		LAST_NM = nrow.LAST_NM,
		MID_INI_NM = nrow.MID_INI_NM,
		NMPRFX_DSC = nrow.NMPRFX_DSC,
		PHONE_NO = nrow.PHONE_NO,
		TEL_EXT_NO = nrow.TEL_EXT_NO,
		START_DT = nrow.START_DT,
		SUFX_TLDSC = nrow.SUFX_TLDSC,
		TLCMTR_IND = nrow.TLCMTR_IND,
		LST_UPD_ID = nrow.LST_UPD_ID,
		LST_UPD_TS = nrow.LST_UPD_TS,
		FKCWS_OFFT = nrow.FKCWS_OFFT,
		AVLOC_DSC = nrow.AVLOC_DSC,
		SSRS_WKRID = nrow.SSRS_WKRID,
		CNTY_SPFCD = nrow.CNTY_SPFCD,
		DTYWKR_IND = nrow.DTYWKR_IND,
		FKCWSADDRT = nrow.FKCWSADDRT,
		EMAIL_ADDR = nrow.EMAIL_ADDR,
		IBMSNAP_OPERATION = 'U',
		IBMSNAP_LOGMARKER = current timestamp
	WHERE IDENTIFIER = nrow.identifier;
END
