-- DROP TABLE CWSRSQ.CMP_ALLGTN ;

CREATE TABLE CWSRSQ.CMP_ALLGTN (
	FKREFERL_T CHAR(10) NOT NULL,
	FKCLIENT_T CHAR(10) NOT NULL, -- VICTIM
	FKCLIENT_0 CHAR(10),          -- PERP
	IDENTIFIER CHAR(10) NOT NULL,
	ALG_DSPC SMALLINT NOT NULL,
	ALG_TPC SMALLINT NOT NULL,
	LST_UPD_ID CHAR(3) NOT NULL,
	LST_UPD_TS TIMESTAMP NOT NULL,
	CNTY_SPFCD CHAR(2) NOT NULL
)
IN DTEMPDB.TSPART  -- DBA will provide
AUDIT NONE DATA CAPTURE NONE NOT VOLATILE 
-- NOT LOGGED       -- tablespace setting
-- COMPRESS YES     -- ditto
-- APPEND YES       -- ditto
PARTITION BY (FKCLIENT_T) (
	PARTITION 1  ENDING AT ('B3bMRWu8NV'),
	PARTITION 2  ENDING AT ('DW5GzxJ30A'),
	PARTITION 3  ENDING AT ('FNOBbaG6qq'),
	PARTITION 4  ENDING AT ('HJf1EJe25X'),
	PARTITION 5  ENDING AT ('JCoyq0Iz36'),
	PARTITION 6  ENDING AT ('LvijYcj01S'),
	PARTITION 7  ENDING AT ('Npf4LcB3Lr'),
	PARTITION 8  ENDING AT ('PiJ6a0H49S'),
	PARTITION 9  ENDING AT ('RbL4aAL34A'),
	PARTITION 10 ENDING AT ('S3qiIdg0BN'),
	PARTITION 11 ENDING AT ('0Ltok9y5Co'),
	PARTITION 12 ENDING AT ('2CFeyJd49S'),
	PARTITION 13 ENDING AT ('4w3QDw136B'),
	PARTITION 14 ENDING AT ('6p9XaHC10S'),
	PARTITION 15 ENDING AT ('8jw5J580MQ'),
	PARTITION 16 ENDING AT ('9999999999')
);

COMMIT ;


SET CURRENT DEGREE = 'ANY' ;


INSERT INTO CWSRSQ.CMP_ALLGTN (FKCLIENT_T, FKREFERL_T, IDENTIFIER, FKCLIENT_0, ALG_DSPC, ALG_TPC, LST_UPD_ID, LST_UPD_TS, CNTY_SPFCD)
SELECT FKCLIENT_T, FKREFERL_T, IDENTIFIER, FKCLIENT_0, ALG_DSPC, ALG_TPC, LST_UPD_ID, LST_UPD_TS, CNTY_SPFCD
FROM CWSRSQ.ALLGTN_T ag;

COMMIT ;

CREATE UNIQUE INDEX CWSRSQ.UIX_CMP_ALLGTN ON CWSRSQ.CMP_ALLGTN (FKCLIENT_T, FKREFERL_T, FKCLIENT_0, IDENTIFIER) PARTITIONED;

COMMIT ;

-- CREATE INDEX CWSRSQ.IX_VCTM_ALLGTN ON CWSRSQ.CMP_ALLGTN (FKREFERL_T, FKCLIENT_T, FKCLIENT_0);


