DROP TRIGGER CWSINT.trg_allgtn_ins;

CREATE TRIGGER CWSINT.trg_allgtn_ins
AFTER INSERT ON CWSINT.ALLGTN_T
REFERENCING NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
INSERT INTO CWSRS1.ALLGTN_T (
	IDENTIFIER,
	ABUSE_ENDT,
	ABUSE_FREQ,
	ABUSE_PDCD,
	LOC_DSC,
	ABUSE_STDT,
	ALG_DSPC,
	ALG_TPC,
	DISPSN_DSC,
	DISPSN_DT,
	IJHM_DET_B,
	NON_PRT_CD,
	STFADD_IND,
	LST_UPD_ID,
	LST_UPD_TS,
	FKCLIENT_T,
	FKCLIENT_0,
	FKREFERL_T,
	CNTY_SPFCD,
	ZIPPY_IND,
	PLC_FCLC,
	IBMSNAP_OPERATION,
	IBMSNAP_LOGMARKER
) VALUES (
	nrow.IDENTIFIER,
	nrow.ABUSE_ENDT,
	nrow.ABUSE_FREQ,
	nrow.ABUSE_PDCD,
	nrow.LOC_DSC,
	nrow.ABUSE_STDT,
	nrow.ALG_DSPC,
	nrow.ALG_TPC,
	nrow.DISPSN_DSC,
	nrow.DISPSN_DT,
	nrow.IJHM_DET_B,
	nrow.NON_PRT_CD,
	nrow.STFADD_IND,
	nrow.LST_UPD_ID,
	nrow.LST_UPD_TS,
	nrow.FKCLIENT_T,
	nrow.FKCLIENT_0,
	nrow.FKREFERL_T,
	nrow.CNTY_SPFCD,
	nrow.ZIPPY_IND,
	nrow.PLC_FCLC,
	'I',
	current timestamp
);
END
