DROP TRIGGER CWSINT.trg_case_upd;

CREATE TRIGGER CWSINT.trg_case_upd
AFTER UPDATE ON CWSINT.CASE_T
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
UPDATE CWSRS1.CASE_T SET 
	IDENTIFIER = nrow.IDENTIFIER,
	START_DT = nrow.START_DT,
	SRV_CMPC = nrow.SRV_CMPC,
	APRVL_NO = nrow.APRVL_NO,
	APV_STC = nrow.APV_STC,
	CLS_RSNC = nrow.CLS_RSNC,
	CSPL_DET_B = nrow.CSPL_DET_B,
	CL_STM_TXT = nrow.CL_STM_TXT,
	CNTRY_C = nrow.CNTRY_C,
	NOTES_DOC = nrow.NOTES_DOC,
	END_DT = nrow.END_DT,
	GVR_ENTC = nrow.GVR_ENTC,
	ICPCSTAT_B = nrow.ICPCSTAT_B,
	ICPC_RQT_B = nrow.ICPC_RQT_B,
	LMT_ACSSCD = nrow.LMT_ACSSCD,
	CASE_NM = nrow.CASE_NM,
	PRJ_END_DT = nrow.PRJ_END_DT,
	SPRJ_CST_B = nrow.SPRJ_CST_B,
	STATE_C = nrow.STATE_C,
	TICKLE_T_B = nrow.TICKLE_T_B,
	LST_UPD_ID = nrow.LST_UPD_ID,
	LST_UPD_TS = nrow.LST_UPD_TS,
	FKCHLD_CLT = nrow.FKCHLD_CLT,
	SRV_CMPDT = nrow.SRV_CMPDT,
	FKSTFPERST = nrow.FKSTFPERST,
	CNTY_SPFCD = nrow.CNTY_SPFCD,
	ALERT_TXT = nrow.ALERT_TXT,
	FKREFERL_T = nrow.FKREFERL_T,
	RSP_AGY_CD = nrow.RSP_AGY_CD,
	NXT_TILPDT = nrow.NXT_TILPDT,
	EMANCPN_DT = nrow.EMANCPN_DT,
	L_GVR_ENTC = nrow.L_GVR_ENTC,
	LMT_ACS_DT = nrow.LMT_ACS_DT,
	LMT_ACSDSC = nrow.LMT_ACSDSC,
	IBMSNAP_OPERATION = 'U',
	IBMSNAP_LOGMARKER = current timestamp
WHERE IDENTIFIER = nrow.identifier;
END
