CREATE TRIGGER CWSINT.trg_ins_claddr
AFTER INSERT ON CL_ADDRT
REFERENCING NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
INSERT INTO CWSRS1.CL_ADDRT (
	IDENTIFIER,
	ADDR_TPC,
	BK_INMT_ID,
	EFF_END_DT,
	EFF_STRTDT,
	LST_UPD_ID,
	LST_UPD_TS,
	FKADDRS_T,
	FKCLIENT_T,
	HOMLES_IND,
	FKREFERL_T,	
	IBMSNAP_OPERATION,
	IBMSNAP_LOGMARKER
) VALUES (
	nrow.IDENTIFIER,
	nrow.ADDR_TPC,
	nrow.BK_INMT_ID,
	nrow.EFF_END_DT,
	nrow.EFF_STRTDT,
	nrow.LST_UPD_ID,
	nrow.LST_UPD_TS,
	nrow.FKADDRS_T,
	nrow.FKCLIENT_T,
	nrow.HOMLES_IND,
	nrow.FKREFERL_T,
	'I',
	current timestamp
);
END


