DROP TRIGGER CWSINT.trg_cln_relt_upd;

CREATE TRIGGER CWSINT.trg_cln_relt_upd
AFTER UPDATE ON CWSINT.CLN_RELT
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
UPDATE CWSRS1.CLN_RELT SET 
	IDENTIFIER = nrow.IDENTIFIER,
	ABSENT_CD = nrow.ABSENT_CD,
	CLNTRELC = nrow.CLNTRELC,
	END_DT = nrow.END_DT,
	SAME_HM_CD = nrow.SAME_HM_CD,
	START_DT = nrow.START_DT,
	LST_UPD_ID = nrow.LST_UPD_ID,
	LST_UPD_TS = nrow.LST_UPD_TS,
	FKCLIENT_T = nrow.FKCLIENT_T,
	FKCLIENT_0 = nrow.FKCLIENT_0,
	IBMSNAP_OPERATION = 'U',
	IBMSNAP_LOGMARKER = current timestamp
WHERE IDENTIFIER = nrow.identifier;
END
