DROP TRIGGER CWSINT.trg_cln_relt_ins;

CREATE TRIGGER CWSINT.trg_cln_relt_ins
AFTER UPDATE ON CWSINT.CLN_RELT
REFERENCING NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
INSERT INTO CWSRS1.CLN_RELT ( 
	IDENTIFIER,
	ABSENT_CD,
	CLNTRELC,
	END_DT,
	SAME_HM_CD,
	START_DT,
	LST_UPD_ID,
	LST_UPD_TS,
	FKCLIENT_T,
	FKCLIENT_0,
	IBMSNAP_OPERATION,
	IBMSNAP_LOGMARKER
) VALUES (
	nrow.IDENTIFIER,
	nrow.ABSENT_CD,
	nrow.CLNTRELC,
	nrow.END_DT,
	nrow.SAME_HM_CD,
	nrow.START_DT,
	nrow.LST_UPD_ID,
	nrow.LST_UPD_TS,
	nrow.FKCLIENT_T,
	nrow.FKCLIENT_0,
	'I',
	current timestamp
);
END
