DROP TRIGGER CWSINT.trg_cln_relt_del;

CREATE TRIGGER CWSINT.trg_cln_relt_del
AFTER DELETE ON CWSINT.CLN_RELT
REFERENCING OLD AS OROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
MERGE INTO CWSRS1.CLN_RELT tgt USING ( 
SELECT
	orow.IDENTIFIER,
	orow.ABSENT_CD,
	orow.CLNTRELC,
	orow.END_DT,
	orow.SAME_HM_CD,
	orow.START_DT,
	orow.LST_UPD_ID,
	orow.LST_UPD_TS,
	orow.FKCLIENT_T,
	orow.FKCLIENT_0
	FROM sysibm.sysdummy1
) X ON (tgt.IDENTIFIER = X.IDENTIFIER)
WHEN MATCHED THEN UPDATE SET 
	IDENTIFIER = x.IDENTIFIER,
	ABSENT_CD = x.ABSENT_CD,
	CLNTRELC = x.CLNTRELC,
	END_DT = x.END_DT,
	SAME_HM_CD = x.SAME_HM_CD,
	START_DT = x.START_DT,
	LST_UPD_ID = x.LST_UPD_ID,
	LST_UPD_TS = x.LST_UPD_TS,
	FKCLIENT_T = x.FKCLIENT_T,
	FKCLIENT_0 = x.FKCLIENT_0,
	IBMSNAP_OPERATION = 'D',
	IBMSNAP_LOGMARKER = current timestamp
WHEN NOT MATCHED THEN INSERT (
	IDENTIFIER,
	ABSENT_CD,
	CLNTRELC,
	END_DT,
	SAME_HM_CD,
	START_DT,
	LST_UPD_ID,
	LST_UPD_TS,
	FKCLIENT_T,
	FKCLIENT_0,
	IBMSNAP_OPERATION,
	IBMSNAP_LOGMARKER
) VALUES (
	x.IDENTIFIER,
	x.ABSENT_CD,
	x.CLNTRELC,
	x.END_DT,
	x.SAME_HM_CD,
	x.START_DT,
	x.LST_UPD_ID,
	x.LST_UPD_TS,
	x.FKCLIENT_T,
	x.FKCLIENT_0,
	'D',
	current timestamp
);
END
