DROP TRIGGER CWSINT.trg_coltrl_t_upd;

CREATE TRIGGER CWSINT.trg_coltrl_t_upd
AFTER UPDATE ON CWSINT.COLTRL_T
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	UPDATE CWSRS1.COLTRL_T SET 
		IDENTIFIER = nrow.IDENTIFIER,
		BADGE_NO = nrow.BADGE_NO,
		CITY_NM = nrow.CITY_NM,
		EMPLYR_NM = nrow.EMPLYR_NM,
		FAX_NO = nrow.FAX_NO,
		FIRST_NM = nrow.FIRST_NM,
		FRG_ADRT_B = nrow.FRG_ADRT_B,
		LAST_NM = nrow.LAST_NM,
		MID_INI_NM = nrow.MID_INI_NM,
		NMPRFX_DSC = nrow.NMPRFX_DSC,
		PRM_TEL_NO = nrow.PRM_TEL_NO,
		PRM_EXT_NO = nrow.PRM_EXT_NO,
		STATE_C = nrow.STATE_C,
		STREET_NM = nrow.STREET_NM,
		STREET_NO = nrow.STREET_NO,
		SUFX_TLDSC = nrow.SUFX_TLDSC,
		ZIP_NO = nrow.ZIP_NO,
		LST_UPD_ID = nrow.LST_UPD_ID,
		LST_UPD_TS = nrow.LST_UPD_TS,
		ZIP_SFX_NO = nrow.ZIP_SFX_NO,
		COMNT_DSC = nrow.COMNT_DSC,
		GENDER_CD = nrow.GENDER_CD,
		BIRTH_DT = nrow.BIRTH_DT,
		MRTL_STC = nrow.MRTL_STC,
		EMAIL_ADDR = nrow.EMAIL_ADDR,
		ESTBLSH_CD = nrow.ESTBLSH_CD,
		ESTBLSH_ID = nrow.ESTBLSH_ID,
		RESOST_IND = nrow.RESOST_IND,
		IBMSNAP_OPERATION = 'U',
		IBMSNAP_LOGMARKER = current timestamp
	WHERE IDENTIFIER = nrow.identifier;
END
