DROP TRIGGER CWSINT.trg_edprvprt_upd;

CREATE TRIGGER CWSINT.trg_edprvprt_upd
AFTER UPDATE ON CWSINT.EDPRVPRT
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	UPDATE CWSRS1.EDPRVPRT SET 
		EDUPRVCD = nrow.EDUPRVCD,
		LST_UPD_ID = nrow.LST_UPD_ID,
		LST_UPD_TS = nrow.LST_UPD_TS,
		FKED_PVDRT = nrow.FKED_PVDRT,
		IBMSNAP_OPERATION = 'U',
		IBMSNAP_LOGMARKER = current timestamp
	WHERE IDENTIFIER = nrow.identifier;
END
