DROP TRIGGER CWSINT.trg_edprvprt_ins;

CREATE TRIGGER CWSINT.trg_edprvprt_ins
AFTER INSERT ON CWSINT.EDPRVPRT
REFERENCING NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	MERGE INTO CWSRS1.EDPRVPRT tgt USING ( 
		SELECT
		nrow.IDENTIFIER,
		nrow.EDUPRVCD,
		nrow.LST_UPD_ID,
		nrow.LST_UPD_TS,
		nrow.FKED_PVDRT
		FROM sysibm.sysdummy1
	) X ON (tgt.IDENTIFIER = X.IDENTIFIER)
	WHEN MATCHED THEN UPDATE SET 
		EDUPRVCD = x.EDUPRVCD,
		LST_UPD_ID = x.LST_UPD_ID,
		LST_UPD_TS = x.LST_UPD_TS,
		FKED_PVDRT = x.FKED_PVDRT,
		IBMSNAP_OPERATION = 'I',
		IBMSNAP_LOGMARKER = current timestamp
	WHEN NOT MATCHED THEN INSERT (
		IDENTIFIER,
		EDUPRVCD,
		LST_UPD_ID,
		LST_UPD_TS,
		FKED_PVDRT,
		IBMSNAP_OPERATION,
		IBMSNAP_LOGMARKER
	) VALUES (
		x.IDENTIFIER,
		x.EDUPRVCD,
		x.LST_UPD_ID,
		x.LST_UPD_TS,
		x.FKED_PVDRT,
		'I',
		current timestamp
	);
END
