DROP TRIGGER CWSINT.trg_edprvprt_ins;

CREATE TRIGGER CWSINT.trg_edprvprt_ins
AFTER UPDATE ON CWSINT.EDPRVPRT
REFERENCING NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
INSERT INTO CWSRS1.EDPRVPRT ( 
	IDENTIFIER,
	EDUPRVCD,
	LST_UPD_ID,
	LST_UPD_TS,
	FKED_PVDRT,
	IBMSNAP_OPERATION,
	IBMSNAP_LOGMARKER
) VALUES (
	nrow.IDENTIFIER,
	nrow.EDUPRVCD,
	nrow.LST_UPD_ID,
	nrow.LST_UPD_TS,
	nrow.FKED_PVDRT,
	'I',
	current timestamp
	);
END
