DROP TRIGGER CWSINT.trg_ocl_nm_t_del;

CREATE TRIGGER CWSINT.trg_ocl_nm_t_del
AFTER DELETE ON CWSINT.OCL_NM_T
REFERENCING OLD AS OROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
MERGE INTO CWSRS1.OCL_NM_T tgt USING ( 
SELECT
	orow.THIRD_ID,
	orow.FIRST_NM,
	orow.LAST_NM,
	orow.MIDDLE_NM,
	orow.NMPRFX_DSC,
	orow.NAME_TPC,
	orow.SUFX_TLDSC,
	orow.LST_UPD_ID,
	orow.LST_UPD_TS,
	orow.FKCLIENT_T
FROM sysibm.sysdummy1
) X ON (tgt.FKCLIENT_T = X.FKCLIENT_T AND tgt.THIRD_ID = X.THIRD_ID)
WHEN MATCHED THEN UPDATE SET 
	FIRST_NM = x.FIRST_NM,
	LAST_NM = x.LAST_NM,
	MIDDLE_NM = x.MIDDLE_NM,
	NMPRFX_DSC = x.NMPRFX_DSC,
	NAME_TPC = x.NAME_TPC,
	SUFX_TLDSC = x.SUFX_TLDSC,
	LST_UPD_ID = x.LST_UPD_ID,
	LST_UPD_TS = x.LST_UPD_TS,
	IBMSNAP_OPERATION = 'D',
	IBMSNAP_LOGMARKER = current timestamp
WHEN NOT MATCHED THEN INSERT (
	THIRD_ID,
	FIRST_NM,
	LAST_NM,
	MIDDLE_NM,
	NMPRFX_DSC,
	NAME_TPC,
	SUFX_TLDSC,
	LST_UPD_ID,
	LST_UPD_TS,
	FKCLIENT_T,
	IBMSNAP_OPERATION,
	IBMSNAP_LOGMARKER
) VALUES (
	x.THIRD_ID,
	x.FIRST_NM,
	x.LAST_NM,
	x.MIDDLE_NM,
	x.NMPRFX_DSC,
	x.NAME_TPC,
	x.SUFX_TLDSC,
	x.LST_UPD_ID,
	x.LST_UPD_TS,
	x.FKCLIENT_T,
	'D',
	current timestamp
);
END
