DROP TRIGGER CWSINT.trg_ocl_nm_t_ins;

CREATE TRIGGER CWSINT.trg_ocl_nm_t_ins
AFTER UPDATE ON CWSINT.OCL_NM_T
REFERENCING NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	INSERT INTO CWSRS1.OCL_NM_T ( 
		THIRD_ID,
		FIRST_NM,
		LAST_NM,
		MIDDLE_NM,
		NMPRFX_DSC,
		NAME_TPC,
		SUFX_TLDSC,
		LST_UPD_ID,
		LST_UPD_TS,
		FKCLIENT_T,
		IBMSNAP_OPERATION,
		IBMSNAP_LOGMARKER
	) VALUES (
		nrow.THIRD_ID,
		nrow.FIRST_NM,
		nrow.LAST_NM,
		nrow.MIDDLE_NM,
		nrow.NMPRFX_DSC,
		nrow.NAME_TPC,
		nrow.SUFX_TLDSC,
		nrow.LST_UPD_ID,
		nrow.LST_UPD_TS,
		nrow.FKCLIENT_T,
		'I',
		current timestamp
	);
END
