DROP TRIGGER CWSINT.trg_oth_kidt_upd;

CREATE TRIGGER CWSINT.trg_oth_kidt_upd
AFTER UPDATE ON CWSINT.OTH_KIDT
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	UPDATE CWSRS1.OTH_KIDT SET 
		BIRTH_DT = nrow.BIRTH_DT,
		GENDER_CD = nrow.GENDER_CD,
		OTHCHLD_NM = nrow.OTHCHLD_NM,
		LST_UPD_ID = nrow.LST_UPD_ID,
		LST_UPD_TS = nrow.LST_UPD_TS,
		FKPLC_HM_T = nrow.FKPLC_HM_T,
		YR_INC_AMT = nrow.YR_INC_AMT,
		IBMSNAP_OPERATION = 'U',
		IBMSNAP_LOGMARKER = current timestamp
	WHERE IDENTIFIER = nrow.identifier;
END
