DROP TRIGGER CWSINT.trg_oth_kidt_ins;

CREATE TRIGGER CWSINT.trg_oth_kidt_ins
AFTER UPDATE ON CWSINT.OTH_KIDT
REFERENCING NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	INSERT INTO CWSRS1.OTH_KIDT ( 
		IDENTIFIER,
		BIRTH_DT,
		GENDER_CD,
		OTHCHLD_NM,
		LST_UPD_ID,
		LST_UPD_TS,
		FKPLC_HM_T,
		YR_INC_AMT,
		IBMSNAP_OPERATION,
		IBMSNAP_LOGMARKER		
	) VALUES (
		nrow.IDENTIFIER,
		nrow.BIRTH_DT,
		nrow.GENDER_CD,
		nrow.OTHCHLD_NM,
		nrow.LST_UPD_ID,
		nrow.LST_UPD_TS,
		nrow.FKPLC_HM_T,
		nrow.YR_INC_AMT,
		'I',
		current timestamp
	);
END
