DROP TRIGGER CWSINT.trg_referl_t_upd;

CREATE TRIGGER CWSINT.trg_referl_t_upd
AFTER UPDATE ON CWSINT.REFERL_T
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	UPDATE CWSRS1.REFERL_T SET 
		ADD_INF_CD = nrow.ADD_INF_CD,
		ANRPTR_IND = nrow.ANRPTR_IND,
		PETAPL_IND = nrow.PETAPL_IND,
		APRVL_NO = nrow.APRVL_NO,
		APV_STC = nrow.APV_STC,
		CR_PERP_CD = nrow.CR_PERP_CD,
		REFCLSR_DT = nrow.REFCLSR_DT,
		CMM_MTHC = nrow.CMM_MTHC,
		CHILOC_TXT = nrow.CHILOC_TXT,
		ALGDSC_DOC = nrow.ALGDSC_DOC,
		ER_REF_DOC = nrow.ER_REF_DOC,
		INVSTG_DOC = nrow.INVSTG_DOC,
		XRPT_LWIND = nrow.XRPT_LWIND,
		FMY_AW_IND = nrow.FMY_AW_IND,
		GVR_ENTC = nrow.GVR_ENTC,
		LGL_DEF_CD = nrow.LGL_DEF_CD,
		LGLRGT_IND = nrow.LGLRGT_IND,
		LMT_ACSSCD = nrow.LMT_ACSSCD,
		XRPT_RCVDT = nrow.XRPT_RCVDT,
		REFERRL_NM = nrow.REFERRL_NM,
		ADQT_CS_CD = nrow.ADQT_CS_CD,
		REF_RCV_DT = nrow.REF_RCV_DT,
		REF_RCV_TM = nrow.REF_RCV_TM,
		RFR_RSPC = nrow.RFR_RSPC,
		RFRD_RSC = nrow.RFRD_RSC,
		RSP_DTR_DT = nrow.RSP_DTR_DT,
		RSP_DTR_TM = nrow.RSP_DTR_TM,
		RSP_RTNTXT = nrow.RSP_RTNTXT,
		SCN_NT_TXT = nrow.SCN_NT_TXT,
		SP_INCL_CD = nrow.SP_INCL_CD,
		SFC_INF_CD = nrow.SFC_INF_CD,
		UNFD_SR_CD = nrow.UNFD_SR_CD,
		LST_UPD_ID = nrow.LST_UPD_ID,
		LST_UPD_TS = nrow.LST_UPD_TS,
		FKREFERL_T = nrow.FKREFERL_T,
		FKADDRS_T = nrow.FKADDRS_T,
		FKSTFPERS0 = nrow.FKSTFPERS0,
		FKSTFPERST = nrow.FKSTFPERST,
		CNTY_SPFCD = nrow.CNTY_SPFCD,
		SPRJRF_IND = nrow.SPRJRF_IND,
		ZIPPY_IND = nrow.ZIPPY_IND,
		HOMLES_IND = nrow.HOMLES_IND,
		FAMREF_IND = nrow.FAMREF_IND,
		FIRST_EODT = nrow.FIRST_EODT,
		RSP_AGY_CD = nrow.RSP_AGY_CD,
		L_GVR_ENTC = nrow.L_GVR_ENTC,
		LMT_ACS_DT = nrow.LMT_ACS_DT,
		LMT_ACSDSC = nrow.LMT_ACSDSC,
		ORIGCLS_DT = nrow.ORIGCLS_DT,
		IBMSNAP_OPERATION = 'U',
		IBMSNAP_LOGMARKER = current timestamp
	WHERE IDENTIFIER = nrow.identifier;
END
