DROP TRIGGER CWSINT.trg_refr_clt_ins;

CREATE TRIGGER CWSINT.trg_refr_clt_ins
AFTER INSERT ON CWSINT.REFR_CLT
REFERENCING NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	MERGE INTO CWSRS1.REFR_CLT tgt USING ( 
		SELECT
			nrow.APRVL_NO,
			nrow.APV_STC,
			nrow.DSP_RSNC,
			nrow.DISPSTN_CD,
			nrow.RCL_DISPDT,
			nrow.SLFRPT_IND,
			nrow.STFADD_IND,
			nrow.LST_UPD_ID,
			nrow.LST_UPD_TS,
			nrow.FKCLIENT_T,
			nrow.FKREFERL_T,
			nrow.DSP_CLSDSC,
			nrow.RFCL_AGENO,
			nrow.AGE_PRD_CD,
			nrow.CNTY_SPFCD,
			nrow.MHLTH_IND,
			nrow.ALCHL_IND,
			nrow.DRUG_IND
		FROM sysibm.sysdummy1
	) X ON (tgt.FKCLIENT_T = X.FKCLIENT_T AND tgt.FKREFERL_T = X.FKREFERL_T)
	WHEN MATCHED THEN UPDATE SET 
		APRVL_NO = x.APRVL_NO,
		APV_STC = x.APV_STC,
		DSP_RSNC = x.DSP_RSNC,
		DISPSTN_CD = x.DISPSTN_CD,
		RCL_DISPDT = x.RCL_DISPDT,
		SLFRPT_IND = x.SLFRPT_IND,
		STFADD_IND = x.STFADD_IND,
		LST_UPD_ID = x.LST_UPD_ID,
		LST_UPD_TS = x.LST_UPD_TS,
		DSP_CLSDSC = x.DSP_CLSDSC,
		RFCL_AGENO = x.RFCL_AGENO,
		AGE_PRD_CD = x.AGE_PRD_CD,
		CNTY_SPFCD = x.CNTY_SPFCD,
		MHLTH_IND = x.MHLTH_IND,
		ALCHL_IND = x.ALCHL_IND,
		DRUG_IND = x.DRUG_IND,
		IBMSNAP_OPERATION = 'I',
		IBMSNAP_LOGMARKER = current timestamp
	WHEN NOT MATCHED THEN INSERT (
		APRVL_NO,
		APV_STC,
		DSP_RSNC,
		DISPSTN_CD,
		RCL_DISPDT,
		SLFRPT_IND,
		STFADD_IND,
		LST_UPD_ID,
		LST_UPD_TS,
		FKCLIENT_T,
		FKREFERL_T,
		DSP_CLSDSC,
		RFCL_AGENO,
		AGE_PRD_CD,
		CNTY_SPFCD,
		MHLTH_IND,
		ALCHL_IND,
		DRUG_IND,
		IBMSNAP_OPERATION,
		IBMSNAP_LOGMARKER
	) VALUES (
		x.APRVL_NO,
		x.APV_STC,
		x.DSP_RSNC,
		x.DISPSTN_CD,
		x.RCL_DISPDT,
		x.SLFRPT_IND,
		x.STFADD_IND,
		x.LST_UPD_ID,
		x.LST_UPD_TS,
		x.FKCLIENT_T,
		x.FKREFERL_T,
		x.DSP_CLSDSC,
		x.RFCL_AGENO,
		x.AGE_PRD_CD,
		x.CNTY_SPFCD,
		x.MHLTH_IND,
		x.ALCHL_IND,
		x.DRUG_IND,
		'I',
		current timestamp
	);
END
