DROP TRIGGER CWSINT.trg_reptr_t_upd;

CREATE TRIGGER CWSINT.trg_reptr_t_upd
AFTER UPDATE ON CWSINT.REPTR_T
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	UPDATE CWSRS1.REPTR_T SET 
		RPTR_BDGNO = nrow.RPTR_BDGNO,
		RPTR_CTYNM = nrow.RPTR_CTYNM,
		COL_RELC = nrow.COL_RELC,
		CMM_MTHC = nrow.CMM_MTHC,
		CNFWVR_IND = nrow.CNFWVR_IND,
		FDBACK_DOC = nrow.FDBACK_DOC,
		RPTR_EMPNM = nrow.RPTR_EMPNM,
		FEEDBCK_DT = nrow.FEEDBCK_DT,
		FB_RQR_IND = nrow.FB_RQR_IND,
		RPTR_FSTNM = nrow.RPTR_FSTNM,
		RPTR_LSTNM = nrow.RPTR_LSTNM,
		MNRPTR_IND = nrow.MNRPTR_IND,
		MSG_EXT_NO = nrow.MSG_EXT_NO,
		MSG_TEL_NO = nrow.MSG_TEL_NO,
		MID_INI_NM = nrow.MID_INI_NM,
		NMPRFX_DSC = nrow.NMPRFX_DSC,
		PRM_TEL_NO = nrow.PRM_TEL_NO,
		PRM_EXT_NO = nrow.PRM_EXT_NO,
		STATE_C = nrow.STATE_C,
		RPTR_ST_NM = nrow.RPTR_ST_NM,
		RPTR_ST_NO = nrow.RPTR_ST_NO,
		SUFX_TLDSC = nrow.SUFX_TLDSC,
		RPTR_ZIPNO = nrow.RPTR_ZIPNO,
		LST_UPD_ID = nrow.LST_UPD_ID,
		LST_UPD_TS = nrow.LST_UPD_TS,
		FKLAW_ENFT = nrow.FKLAW_ENFT,
		ZIP_SFX_NO = nrow.ZIP_SFX_NO,
		CNTY_SPFCD = nrow.CNTY_SPFCD,
		IBMSNAP_OPERATION = 'U',
		IBMSNAP_LOGMARKER = current timestamp
	WHERE FKREFERL_T = nrow.FKREFERL_T;
END
