DROP TRIGGER CWSINT.trg_sb_pvdrt_upd;

CREATE TRIGGER CWSINT.trg_sb_pvdrt_upd
AFTER UPDATE ON CWSINT.SB_PVDRT
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	UPDATE CWSRS1.SB_PVDRT SET 
		ADD_TEL_NO = nrow.ADD_TEL_NO,
		ADD_EXT_NO = nrow.ADD_EXT_NO,
		BIRTH_DT = nrow.BIRTH_DT,
		CA_DLIC_NO = nrow.CA_DLIC_NO,
		CITY_NM = nrow.CITY_NM,
		EMPLYR_NM = nrow.EMPLYR_NM,
		FIRST_NM = nrow.FIRST_NM,
		FRG_ADRT_B = nrow.FRG_ADRT_B,
		GENDER_IND = nrow.GENDER_IND,
		IND_TRBC = nrow.IND_TRBC,
		LAST_NM = nrow.LAST_NM,
		MID_INI_NM = nrow.MID_INI_NM,
		NMPRFX_DSC = nrow.NMPRFX_DSC,
		SS_NO = nrow.SS_NO,
		STATE_C = nrow.STATE_C,
		STREET_NM = nrow.STREET_NM,
		STREET_NO = nrow.STREET_NO,
		SUFX_TLDSC = nrow.SUFX_TLDSC,
		ZIP_NO = nrow.ZIP_NO,
		LST_UPD_ID = nrow.LST_UPD_ID,
		LST_UPD_TS = nrow.LST_UPD_TS,
		ZIP_SFX_NO = nrow.ZIP_SFX_NO,
		EDUCATION = nrow.EDUCATION,
		EMPL_STAT = nrow.EMPL_STAT,
		PRIM_INC = nrow.PRIM_INC,
		SEC_INC = nrow.SEC_INC,
		YR_INC_AMT = nrow.YR_INC_AMT,
		HISP_CD = nrow.HISP_CD,
		MRTL_STC = nrow.MRTL_STC,
		LISOWNIND = nrow.LISOWNIND,
		LIS_PER_ID = nrow.LIS_PER_ID,
		EMAIL_ADDR = nrow.EMAIL_ADDR,
		ETH_UD_CD = nrow.ETH_UD_CD,
		HISP_UD_CD = nrow.HISP_UD_CD,
		RESOST_IND = nrow.RESOST_IND,
		PASSBC_CD = nrow.PASSBC_CD,
		IBMSNAP_OPERATION = 'U',
		IBMSNAP_LOGMARKER = current timestamp
	WHERE IDENTIFIER = nrow.identifier;
END
