DROP TRIGGER CWSINT.trg_stfperst_ins;

CREATE TRIGGER CWSINT.trg_stfperst_ins
AFTER UPDATE ON CWSINT.STFPERST
REFERENCING NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	INSERT INTO CWSRS1.STFPERST ( 
		IDENTIFIER,
		END_DT,
		FIRST_NM,
		JOB_TL_DSC,
		LAST_NM,
		MID_INI_NM,
		NMPRFX_DSC,
		PHONE_NO,
		TEL_EXT_NO,
		START_DT,
		SUFX_TLDSC,
		TLCMTR_IND,
		LST_UPD_ID,
		LST_UPD_TS,
		FKCWS_OFFT,
		AVLOC_DSC,
		SSRS_WKRID,
		CNTY_SPFCD,
		DTYWKR_IND,
		FKCWSADDRT,
		EMAIL_ADDR,
		IBMSNAP_OPERATION,
		IBMSNAP_LOGMARKER
	) VALUES (
		nrow.IDENTIFIER,
		nrow.END_DT,
		nrow.FIRST_NM,
		nrow.JOB_TL_DSC,
		nrow.LAST_NM,
		nrow.MID_INI_NM,
		nrow.NMPRFX_DSC,
		nrow.PHONE_NO,
		nrow.TEL_EXT_NO,
		nrow.START_DT,
		nrow.SUFX_TLDSC,
		nrow.TLCMTR_IND,
		nrow.LST_UPD_ID,
		nrow.LST_UPD_TS,
		nrow.FKCWS_OFFT,
		nrow.AVLOC_DSC,
		nrow.SSRS_WKRID,
		nrow.CNTY_SPFCD,
		nrow.DTYWKR_IND,
		nrow.FKCWSADDRT,
		nrow.EMAIL_ADDR,
		'I',
		current timestamp
	);
END
