DROP TRIGGER CWSINT.trg_svc_pvrt_upd;

CREATE TRIGGER CWSINT.trg_svc_pvrt_upd
AFTER UPDATE ON CWSINT.SVC_PVRT
REFERENCING OLD AS OROW
            NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	UPDATE CWSRS1.SVC_PVRT SET 
		AGENCY_NM = nrow.AGENCY_NM,
		CITY_NM = nrow.CITY_NM,
		FAX_NO = nrow.FAX_NO,
		FIRST_NM = nrow.FIRST_NM,
		LAST_NM = nrow.LAST_NM,
		NMPRFX_DSC = nrow.NMPRFX_DSC,
		PHONE_NO = nrow.PHONE_NO,
		TEL_EXT_NO = nrow.TEL_EXT_NO,
		PSTITL_DSC = nrow.PSTITL_DSC,
		SVCPVDRC = nrow.SVCPVDRC,
		STATE_C = nrow.STATE_C,
		STREET_NM = nrow.STREET_NM,
		STREET_NO = nrow.STREET_NO,
		SUFX_TLDSC = nrow.SUFX_TLDSC,
		ZIP_NM = nrow.ZIP_NM,
		LST_UPD_ID = nrow.LST_UPD_ID,
		LST_UPD_TS = nrow.LST_UPD_TS,
		ZIP_SFX_NO = nrow.ZIP_SFX_NO,
		ARCASS_IND = nrow.ARCASS_IND,
		EMAIL_ADDR = nrow.EMAIL_ADDR,
		IBMSNAP_OPERATION = 'U',
		IBMSNAP_LOGMARKER = current timestamp
	WHERE IDENTIFIER = nrow.identifier;
END
