DROP TRIGGER CWSINT.trg_svc_pvrt_ins;

CREATE TRIGGER CWSINT.trg_svc_pvrt_ins
AFTER UPDATE ON CWSINT.SVC_PVRT
REFERENCING NEW AS NROW
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
	INSERT INTO CWSRS1.SVC_PVRT ( 
		IDENTIFIER,
		AGENCY_NM,
		CITY_NM,
		FAX_NO,
		FIRST_NM,
		LAST_NM,
		NMPRFX_DSC,
		PHONE_NO,
		TEL_EXT_NO,
		PSTITL_DSC,
		SVCPVDRC,
		STATE_C,
		STREET_NM,
		STREET_NO,
		SUFX_TLDSC,
		ZIP_NM,
		LST_UPD_ID,
		LST_UPD_TS,
		ZIP_SFX_NO,
		ARCASS_IND,
		EMAIL_ADDR,
		IBMSNAP_OPERATION,
		IBMSNAP_LOGMARKER
	) VALUES (
		nrow.IDENTIFIER,
		nrow.AGENCY_NM,
		nrow.CITY_NM,
		nrow.FAX_NO,
		nrow.FIRST_NM,
		nrow.LAST_NM,
		nrow.NMPRFX_DSC,
		nrow.PHONE_NO,
		nrow.TEL_EXT_NO,
		nrow.PSTITL_DSC,
		nrow.SVCPVDRC,
		nrow.STATE_C,
		nrow.STREET_NM,
		nrow.STREET_NO,
		nrow.SUFX_TLDSC,
		nrow.ZIP_NM,
		nrow.LST_UPD_ID,
		nrow.LST_UPD_TS,
		nrow.ZIP_SFX_NO,
		nrow.ARCASS_IND,
		nrow.EMAIL_ADDR,
		'I',
		current timestamp
	);
END
