--DROP TABLE CWSRS1.MQT_CMP_CLIENT;

CREATE TABLE CWSRS1.MQT_CMP_CLIENT AS (
	SELECT
		IDENTIFIER,
		cast(trim(SS_NO)      as VARCHAR(20)) as SS_NO,
		SENSTV_IND,
		BIRTH_DT,
		cast(trim(COM_FST_NM) as VARCHAR(20)) as COM_FST_NM,
		cast(trim(COM_LST_NM) as VARCHAR(25)) as COM_LST_NM,
		cast(trim(COM_MID_NM) as VARCHAR(20)) as COM_MID_NM,
		cast(trim(NMPRFX_DSC) as VARCHAR(6))  as NMPRFX_DSC,
		NAME_TPC,
		cast(trim(SUFX_TLDSC) as VARCHAR(4))  as SUFX_TLDSC,
		GENDER_CD,
		P_ETHNCTYC,
		P_LANG_TPC,
		S_LANG_TC,
		cast(trim(EMAIL_ADDR) as VARCHAR(50)) as EMAIL_ADDR,
		CREATN_DT,
		LST_UPD_ID,
		LST_UPD_TS 
	FROM CWSRSQ.CLIENT_T
)
DATA INITIALLY DEFERRED
REFRESH DEFERRED
DISABLE QUERY OPTIMIZATION
--IN DTEMPDB.TSPART
AUDIT NONE DATA CAPTURE NONE NOT VOLATILE 
NOT LOGGED COMPRESS YES APPEND YES
PARTITION BY (IDENTIFIER) (
	PARTITION 1  ENDING AT ('CpE9999999'),
	PARTITION 2  ENDING AT ('EE99999998'),
	PARTITION 3  ENDING AT ('GUE9999997'),
	PARTITION 4  ENDING AT ('I999999996'),
	PARTITION 5  ENDING AT ('LpE9999995'),
	PARTITION 6  ENDING AT ('NE99999994'),
	PARTITION 7  ENDING AT ('PUE9999993'),
	PARTITION 8  ENDING AT ('R999999992'),
	PARTITION 9  ENDING AT ('UpE9999991'),
	PARTITION 10 ENDING AT ('WE99999990'),
	PARTITION 11 ENDING AT ('YUE999999Z'),
	PARTITION 12 ENDING AT ('099999999Y'),
	PARTITION 13 ENDING AT ('3pE999999X'),
	PARTITION 14 ENDING AT ('5E9999999W'),
	PARTITION 15 ENDING AT ('7UE999999V'),
	PARTITION 16 ENDING AT ('9999999999')
);


REFRESH TABLE CWSRS1.MQT_CMP_CLIENT;

CREATE INDEX CWSRS1.IX_MQT_CMP_CLIENT  ON CWSRS1.MQT_CMP_CLIENT (IDENTIFIER, SENSTV_IND) PARTITIONED;

CREATE INDEX CWSRS1.IX2_MQT_CMP_CLIENT ON CWSRS1.MQT_CMP_CLIENT (IDENTIFIER) PARTITIONED;

COMMIT ;

