-- DROP TABLE CWSRS1.MQT_CMP_REFR_CLT;

CREATE TABLE CWSRS1.MQT_CMP_REFR_CLT AS ( 
	SELECT FKREFERL_T, FKCLIENT_T, SENSTV_IND
	FROM CWSRSQ.REFR_CLT rc
	JOIN CWSRSQ.CLIENT_T  c on c.IDENTIFIER = rc.FKCLIENT_T
)
DATA INITIALLY DEFERRED
REFRESH DEFERRED
DISABLE QUERY OPTIMIZATION
--IN DTEMPDB.TSPART
AUDIT NONE DATA CAPTURE NONE NOT VOLATILE 
NOT LOGGED COMPRESS YES APPEND YES;


REFRESH TABLE CWSRS1.MQT_CMP_REFR_CLT;


CREATE INDEX CWSRS1.UIX_MCMP_REFR_CLT  ON CWSRS1.MQT_CMP_REFR_CLT (FKREFERL_T, FKCLIENT_T) ;

CREATE INDEX CWSRS1.UIX2_MCMP_REFR_CLT ON CWSRS1.MQT_CMP_REFR_CLT (FKCLIENT_T, FKREFERL_T) ;

