-- DB2 View/MQT

DROP TABLE CWSRS1.MQT_REL_CLN_RELT_CLIENT;

CREATE TABLE CWSRS1.MQT_REL_CLN_RELT_CLIENT AS (
      SELECT
            'CLN_RELT'              AS THIS_LEGACY_TABLE,
            'CLIENT_T'              AS RELATED_LEGACY_TABLE,
            CLNS.IDENTIFIER         AS THIS_LEGACY_ID,
            CLNS.SENSTV_IND         AS THIS_SENSITIVITY_IND,            
            CLNS.LST_UPD_ID         AS THIS_LEGACY_LAST_UPDATED_ID,
            CLNS.LST_UPD_TS         AS THIS_LEGACY_LAST_UPDATED,                                    
            CLNS.COM_FST_NM         AS THIS_FIRST_NAME,
            CLNS.COM_LST_NM         AS THIS_LAST_NAME,
            CLNR.CLNTRELC           AS REL_CODE,
            CLNP.IDENTIFIER         AS RELATED_LEGACY_ID,
            CLNP.SENSTV_IND         AS RELATED_SENSITIVITY_IND,            
            CLNP.LST_UPD_ID         AS RELATED_LEGACY_LAST_UPDATED_ID,
            CLNP.LST_UPD_TS         AS RELATED_LEGACY_LAST_UPDATED,                        
            CLNP.COM_FST_NM         AS RELATED_FIRST_NAME,
            CLNP.COM_LST_NM         AS RELATED_LAST_NAME,            
            CLNS.IBMSNAP_LOGMARKER  AS THIS_IBMSNAP_LOGMARKER,
            CLNS.IBMSNAP_OPERATION  AS THIS_IBMSNAP_OPERATION,
            CLNP.IBMSNAP_LOGMARKER  AS RELATED_IBMSNAP_LOGMARKER,
            CLNP.IBMSNAP_OPERATION  AS RELATED_IBMSNAP_OPERATION,            
            MAX(CLNR.IBMSNAP_LOGMARKER, CLNP.IBMSNAP_LOGMARKER, CLNS.IBMSNAP_LOGMARKER) AS last_chg
      FROM CWSRS1.CLN_RELT CLNR
      JOIN CWSRS1.CLIENT_T CLNS     ON CLNR.FKCLIENT_T = CLNS.IDENTIFIER
      JOIN CWSRS1.CLIENT_T CLNP     ON CLNR.FKCLIENT_0 = CLNP.IDENTIFIER
)
DATA INITIALLY DEFERRED
REFRESH DEFERRED
DISABLE QUERY OPTIMIZATION ;

-- Execute on linux hosts:
SET INTEGRITY FOR CWSRS1.MQT_REL_CLN_RELT_CLIENT MATERIALIZED QUERY IMMEDIATE UNCHECKED;

REFRESH TABLE CWSRS1.MQT_REL_CLN_RELT_CLIENT;
