--==========================
-- TEST TRIGGERS: CLIENT_T:
--==========================

-------------
-- EXISTS: 
-------------

BEGIN ATOMIC

	DECLARE v_tgt_id char(10);
	DECLARE v_src_id char(10);
	DECLARE v_op     char(1);
	DECLARE v_chg    char(1);

	SET v_tgt_id = 'AaiU7IW0Rt';
	SET v_src_id = 'AapJGAU04Z'; -- test re-insert
	
	UPDATE CWSINT.CLIENT_T r
	SET 
	    r.CHLD_CLT_B   = 'Y',
	    r.LST_UPD_ID   = '0x5',
	    r.LST_UPD_TS   = current timestamp
	WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CHLD_CLT_B FROM CWSRS1.CLIENT_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'U' OR v_chg != 'Y') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: update existing';
	END IF;

	DELETE FROM CWSINT.CLIENT_T r WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CHLD_CLT_B FROM CWSRS1.CLIENT_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'D' OR v_chg != 'Y') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: delete existing';
	END IF;

	INSERT INTO CWSINT.CLIENT_T (IDENTIFIER, ADPTN_STCD, ALN_REG_NO, BIRTH_DT, BR_FAC_NM, B_STATE_C, B_CNTRY_C, CHLD_CLT_B, COM_FST_NM, COM_LST_NM, COM_MID_NM, CONF_EFIND, CONF_ACTDT, CREATN_DT, DEATH_DT, DTH_RN_TXT, DRV_LIC_NO, D_STATE_C, GENDER_CD, I_CNTRY_C, IMGT_STC, INCAPC_CD, LITRATE_CD, MAR_HIST_B, MRTL_STC, MILT_STACD, NMPRFX_DSC, NAME_TPC, OUTWRT_IND, P_ETHNCTYC, P_LANG_TPC, RLGN_TPC, S_LANG_TC, SENSTV_IND, SNTV_HLIND, SS_NO, SSN_CHG_CD, SUFX_TLDSC, UNEMPLY_CD, LST_UPD_ID, LST_UPD_TS, COMMNT_DSC, EST_DOB_CD, BP_VER_IND, HISP_CD, CURRCA_IND, CURREG_IND, COTH_DESC, PREVCA_IND, PREREG_IND, POTH_DESC, HCARE_IND, LIMIT_IND, BIRTH_CITY, HEALTH_TXT, MTERM_DT, FTERM_DT, ZIPPY_IND, DEATH_PLC, TR_MBVRT_B, TRBA_CLT_B, SOC158_IND, DTH_DT_IND, EMAIL_ADDR, ADJDEL_IND, ETH_UD_CD, HISP_UD_CD, SOCPLC_CD, CL_INDX_NO)
	SELECT 
	    v_tgt_id as IDENTIFIER,
		ADPTN_STCD, ALN_REG_NO, BIRTH_DT, BR_FAC_NM, B_STATE_C, B_CNTRY_C, CHLD_CLT_B, COM_FST_NM, COM_LST_NM, COM_MID_NM, CONF_EFIND, CONF_ACTDT, CREATN_DT, DEATH_DT, DTH_RN_TXT, DRV_LIC_NO, D_STATE_C, GENDER_CD, I_CNTRY_C, IMGT_STC, INCAPC_CD, LITRATE_CD, MAR_HIST_B, MRTL_STC, MILT_STACD, NMPRFX_DSC, NAME_TPC, OUTWRT_IND, P_ETHNCTYC, P_LANG_TPC, RLGN_TPC, S_LANG_TC, SENSTV_IND, SNTV_HLIND, SS_NO, SSN_CHG_CD, SUFX_TLDSC, UNEMPLY_CD, LST_UPD_ID, LST_UPD_TS, COMMNT_DSC, EST_DOB_CD, BP_VER_IND, HISP_CD, CURRCA_IND, CURREG_IND, COTH_DESC, PREVCA_IND, PREREG_IND, POTH_DESC, HCARE_IND, LIMIT_IND, BIRTH_CITY, HEALTH_TXT, MTERM_DT, FTERM_DT, ZIPPY_IND, DEATH_PLC, TR_MBVRT_B, TRBA_CLT_B, SOC158_IND, DTH_DT_IND, EMAIL_ADDR, ADJDEL_IND, ETH_UD_CD, HISP_UD_CD, SOCPLC_CD, CL_INDX_NO
	FROM CWSINT.CLIENT_T x
	WHERE x.IDENTIFIER = v_src_id ;
	
	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CHLD_CLT_B FROM CWSRS1.CLIENT_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'I') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: insert existing';
	END IF;

END;


rollback;


-------------
-- NEW: 
-------------

BEGIN ATOMIC

	DECLARE v_tgt_id  char(10);
	DECLARE v_src_id  char(10);
	DECLARE v_op      char(1);
	DECLARE v_chg     char(1);

	SET v_tgt_id = '02iU6I6XXX';
	SET v_src_id = 'AapJGAU04Z'; -- test re-insert
	
	INSERT INTO CWSINT.CLIENT_T (IDENTIFIER, ADPTN_STCD, ALN_REG_NO, BIRTH_DT, BR_FAC_NM, B_STATE_C, B_CNTRY_C, CHLD_CLT_B, COM_FST_NM, COM_LST_NM, COM_MID_NM, CONF_EFIND, CONF_ACTDT, CREATN_DT, DEATH_DT, DTH_RN_TXT, DRV_LIC_NO, D_STATE_C, GENDER_CD, I_CNTRY_C, IMGT_STC, INCAPC_CD, LITRATE_CD, MAR_HIST_B, MRTL_STC, MILT_STACD, NMPRFX_DSC, NAME_TPC, OUTWRT_IND, P_ETHNCTYC, P_LANG_TPC, RLGN_TPC, S_LANG_TC, SENSTV_IND, SNTV_HLIND, SS_NO, SSN_CHG_CD, SUFX_TLDSC, UNEMPLY_CD, LST_UPD_ID, LST_UPD_TS, COMMNT_DSC, EST_DOB_CD, BP_VER_IND, HISP_CD, CURRCA_IND, CURREG_IND, COTH_DESC, PREVCA_IND, PREREG_IND, POTH_DESC, HCARE_IND, LIMIT_IND, BIRTH_CITY, HEALTH_TXT, MTERM_DT, FTERM_DT, ZIPPY_IND, DEATH_PLC, TR_MBVRT_B, TRBA_CLT_B, SOC158_IND, DTH_DT_IND, EMAIL_ADDR, ADJDEL_IND, ETH_UD_CD, HISP_UD_CD, SOCPLC_CD, CL_INDX_NO)
	SELECT 
	    v_tgt_id as IDENTIFIER,
		ADPTN_STCD, ALN_REG_NO, BIRTH_DT, BR_FAC_NM, B_STATE_C, B_CNTRY_C, CHLD_CLT_B, COM_FST_NM, COM_LST_NM, COM_MID_NM, CONF_EFIND, CONF_ACTDT, CREATN_DT, DEATH_DT, DTH_RN_TXT, DRV_LIC_NO, D_STATE_C, GENDER_CD, I_CNTRY_C, IMGT_STC, INCAPC_CD, LITRATE_CD, MAR_HIST_B, MRTL_STC, MILT_STACD, NMPRFX_DSC, NAME_TPC, OUTWRT_IND, P_ETHNCTYC, P_LANG_TPC, RLGN_TPC, S_LANG_TC, SENSTV_IND, SNTV_HLIND, SS_NO, SSN_CHG_CD, SUFX_TLDSC, UNEMPLY_CD, LST_UPD_ID, LST_UPD_TS, COMMNT_DSC, EST_DOB_CD, BP_VER_IND, HISP_CD, CURRCA_IND, CURREG_IND, COTH_DESC, PREVCA_IND, PREREG_IND, POTH_DESC, HCARE_IND, LIMIT_IND, BIRTH_CITY, HEALTH_TXT, MTERM_DT, FTERM_DT, ZIPPY_IND, DEATH_PLC, TR_MBVRT_B, TRBA_CLT_B, SOC158_IND, DTH_DT_IND, EMAIL_ADDR, ADJDEL_IND, ETH_UD_CD, HISP_UD_CD, SOCPLC_CD, CL_INDX_NO
	FROM CWSINT.CLIENT_T x
	WHERE x.IDENTIFIER = v_src_id ;
		
	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CHLD_CLT_B FROM CWSRS1.CLIENT_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'I') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: insert new';
	END IF;

	UPDATE CWSINT.CLIENT_T r
	SET 
	    r.CHLD_CLT_B   = 'Y',
	    r.LST_UPD_ID   = '0x5',
	    r.LST_UPD_TS   = current timestamp
	WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CHLD_CLT_B FROM CWSRS1.CLIENT_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'U' OR v_chg != 'Y') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: update new';
	END IF;

	DELETE FROM CWSINT.CLIENT_T r WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CHLD_CLT_B FROM CWSRS1.CLIENT_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'D') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: delete new';
	END IF;

END;


rollback;




