--==========================
-- TEST TRIGGERS: REFERL_T:
--==========================

-------------
-- EXISTS: 
-------------

BEGIN ATOMIC

	DECLARE v_tgt_id char(10);
	DECLARE v_src_id char(10);
	DECLARE v_op     char(1);
	DECLARE v_chg    char(1);

	SET v_tgt_id = 'H4LlQDyCON';
	SET v_src_id = 'H4OtxOa0Py'; -- test re-insert
	
	UPDATE CWSINT.REFERL_T r
	SET 
	    r.ANRPTR_IND   = 'M',
	    r.LST_UPD_ID   = '0x5',
	    r.LST_UPD_TS   = current timestamp
	WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.ANRPTR_IND FROM CWSRS1.REFERL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'U' OR v_chg != 'M') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: update existing';
	END IF;

	DELETE FROM CWSINT.REFERL_T r WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.ANRPTR_IND FROM CWSRS1.REFERL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'D' OR v_chg != 'M') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: delete existing';
	END IF;

	INSERT INTO CWSINT.REFERL_T (IDENTIFIER,ADD_INF_CD,ANRPTR_IND,PETAPL_IND,APRVL_NO,APV_STC,CR_PERP_CD,REFCLSR_DT,CMM_MTHC,CHILOC_TXT,ALGDSC_DOC,ER_REF_DOC,INVSTG_DOC,XRPT_LWIND,FMY_AW_IND,GVR_ENTC,LGL_DEF_CD,LGLRGT_IND,LMT_ACSSCD,XRPT_RCVDT,REFERRL_NM,ADQT_CS_CD,REF_RCV_DT,REF_RCV_TM,RFR_RSPC,RFRD_RSC,RSP_DTR_DT,RSP_DTR_TM,RSP_RTNTXT,SCN_NT_TXT,SP_INCL_CD,SFC_INF_CD,UNFD_SR_CD,LST_UPD_ID,LST_UPD_TS,FKREFERL_T,FKADDRS_T,FKSTFPERS0,FKSTFPERST,CNTY_SPFCD,SPRJRF_IND,ZIPPY_IND,HOMLES_IND,FAMREF_IND,FIRST_EODT,RSP_AGY_CD,L_GVR_ENTC,LMT_ACS_DT,LMT_ACSDSC,ORIGCLS_DT)
	SELECT 
	    v_tgt_id as IDENTIFIER,
		ADD_INF_CD,ANRPTR_IND,PETAPL_IND,APRVL_NO,APV_STC,CR_PERP_CD,REFCLSR_DT,CMM_MTHC,CHILOC_TXT,ALGDSC_DOC,ER_REF_DOC,INVSTG_DOC,XRPT_LWIND,FMY_AW_IND,GVR_ENTC,LGL_DEF_CD,LGLRGT_IND,LMT_ACSSCD,XRPT_RCVDT,REFERRL_NM,ADQT_CS_CD,REF_RCV_DT,REF_RCV_TM,RFR_RSPC,RFRD_RSC,RSP_DTR_DT,RSP_DTR_TM,RSP_RTNTXT,SCN_NT_TXT,SP_INCL_CD,SFC_INF_CD,UNFD_SR_CD,LST_UPD_ID,LST_UPD_TS,FKREFERL_T,FKADDRS_T,FKSTFPERS0,FKSTFPERST,CNTY_SPFCD,SPRJRF_IND,ZIPPY_IND,HOMLES_IND,FAMREF_IND,FIRST_EODT,RSP_AGY_CD,L_GVR_ENTC,LMT_ACS_DT,LMT_ACSDSC,ORIGCLS_DT
	FROM CWSINT.REFERL_T x
	WHERE x.IDENTIFIER = v_src_id ;
	
	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.ANRPTR_IND FROM CWSRS1.REFERL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'I') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: insert existing';
	END IF;

END;


rollback;


-------------
-- NEW: 
-------------

BEGIN ATOMIC

	DECLARE v_tgt_id  char(10);
	DECLARE v_src_id  char(10);
	DECLARE v_op      char(1);
	DECLARE v_chg     char(1);

	SET v_tgt_id = '02iU6I6XXX';
	SET v_src_id = 'H4OtxOa0Py'; -- test re-insert
	
	INSERT INTO CWSINT.REFERL_T (IDENTIFIER,ADD_INF_CD,ANRPTR_IND,PETAPL_IND,APRVL_NO,APV_STC,CR_PERP_CD,REFCLSR_DT,CMM_MTHC,CHILOC_TXT,ALGDSC_DOC,ER_REF_DOC,INVSTG_DOC,XRPT_LWIND,FMY_AW_IND,GVR_ENTC,LGL_DEF_CD,LGLRGT_IND,LMT_ACSSCD,XRPT_RCVDT,REFERRL_NM,ADQT_CS_CD,REF_RCV_DT,REF_RCV_TM,RFR_RSPC,RFRD_RSC,RSP_DTR_DT,RSP_DTR_TM,RSP_RTNTXT,SCN_NT_TXT,SP_INCL_CD,SFC_INF_CD,UNFD_SR_CD,LST_UPD_ID,LST_UPD_TS,FKREFERL_T,FKADDRS_T,FKSTFPERS0,FKSTFPERST,CNTY_SPFCD,SPRJRF_IND,ZIPPY_IND,HOMLES_IND,FAMREF_IND,FIRST_EODT,RSP_AGY_CD,L_GVR_ENTC,LMT_ACS_DT,LMT_ACSDSC,ORIGCLS_DT)
	SELECT 
	    v_tgt_id as IDENTIFIER,
		ADD_INF_CD,ANRPTR_IND,PETAPL_IND,APRVL_NO,APV_STC,CR_PERP_CD,REFCLSR_DT,CMM_MTHC,CHILOC_TXT,ALGDSC_DOC,ER_REF_DOC,INVSTG_DOC,XRPT_LWIND,FMY_AW_IND,GVR_ENTC,LGL_DEF_CD,LGLRGT_IND,LMT_ACSSCD,XRPT_RCVDT,REFERRL_NM,ADQT_CS_CD,REF_RCV_DT,REF_RCV_TM,RFR_RSPC,RFRD_RSC,RSP_DTR_DT,RSP_DTR_TM,RSP_RTNTXT,SCN_NT_TXT,SP_INCL_CD,SFC_INF_CD,UNFD_SR_CD,LST_UPD_ID,LST_UPD_TS,FKREFERL_T,FKADDRS_T,FKSTFPERS0,FKSTFPERST,CNTY_SPFCD,SPRJRF_IND,ZIPPY_IND,HOMLES_IND,FAMREF_IND,FIRST_EODT,RSP_AGY_CD,L_GVR_ENTC,LMT_ACS_DT,LMT_ACSDSC,ORIGCLS_DT
	FROM CWSINT.REFERL_T x
	WHERE x.IDENTIFIER = v_src_id ;
	
	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.ANRPTR_IND FROM CWSRS1.REFERL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'I') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: insert new';
	END IF;

	UPDATE CWSINT.REFERL_T r
	SET 
	    r.ANRPTR_IND   = 'M',
	    r.LST_UPD_ID   = '0x5',
	    r.LST_UPD_TS   = current timestamp
	WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.ANRPTR_IND FROM CWSRS1.REFERL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'U' OR v_chg != 'M') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: update new';
	END IF;

	DELETE FROM CWSINT.REFERL_T r WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.ANRPTR_IND FROM CWSRS1.REFERL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'D') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: delete new';
	END IF;

END;


rollback;




