
SET CURRENT SCHEMA = 'CWSRS1' ;

CREATE GLOBAL TEMPORARY TABLE GT_ID ( 
	IDENTIFIER	CHAR(10) NOT NULL
);

GRANT ALL PRIVILEGES ON CWSRS1.gt_id to cwdsns1;
GRANT ALL PRIVILEGES ON CWSRS1.gt_id to cwdsns2;
GRANT ALL PRIVILEGES ON CWSRS1.gt_id to cwdsns3;
GRANT ALL PRIVILEGES ON CWSRS1.gt_id to cwdsns4;
GRANT ALL PRIVILEGES ON CWSRS1.gt_id to cwdsns5;

