-- DROP TABLE CWSRS1.GT_REFR_CLT;

CREATE GLOBAL TEMPORARY TABLE CWSRS1.GT_REFR_CLT ( 
	FKREFERL_T  CHAR(10) NOT NULL,
	FKCLIENT_T  CHAR(10) NOT NULL,
	SENSTV_IND 	CHAR(1)  NOT NULL
);


CREATE INDEX CWSRS1.IX_GT_REFR_CLT  ON CWSRS1.GT_REFR_CLT (FKREFERL_T, FKCLIENT_T) ;

CREATE INDEX CWSRS1.IX2_GT_REFR_CLT ON CWSRS1.GT_REFR_CLT (FKCLIENT_T, FKREFERL_T) ;

