DROP VIEW CWSRS1.VW_LST_OTHER_CLIENT_NAME;

CREATE VIEW CWSRS1.VW_LST_OTHER_CLIENT_NAME (
  THIRD_ID, 
  FIRST_NM, 
  LAST_NM, 
  MIDDLE_NM, 
  NMPRFX_DSC,
  NAME_TPC, 
  SUFX_TLDSC, 
  LST_UPD_ID, 
  LST_UPD_TS, 
  FKCLIENT_T,   
  IBMSNAP_OPERATION, 
  IBMSNAP_LOGMARKER,
  CLIENT_SENSITIVITY_IND,
  LAST_CHG
) AS 
SELECT 
  ONM.THIRD_ID AS THIRD_ID, 
  ONM.FIRST_NM AS FIRST_NM, 
  ONM.LAST_NM AS LAST_NM, 
  ONM.MIDDLE_NM AS MIDDLE_NM, 
  ONM.NMPRFX_DSC AS NMPRFX_DSC,
  ONM.NAME_TPC AS NAME_TPC, 
  ONM.SUFX_TLDSC AS SUFX_TLDSC, 
  ONM.LST_UPD_ID AS LST_UPD_ID, 
  ONM.LST_UPD_TS AS LST_UPD_TS, 
  ONM.FKCLIENT_T AS FKCLIENT_T,   
  ONM.IBMSNAP_OPERATION AS IBMSNAP_OPERATION, 
  ONM.IBMSNAP_LOGMARKER AS IBMSNAP_LOGMARKER,
  CLT.SENSTV_IND AS CLIENT_SENSITIVITY_IND,
  MAX(ONM.IBMSNAP_LOGMARKER, CLT.IBMSNAP_LOGMARKER) LAST_CHG
FROM CWSRS1.OCL_NM_T ONM
JOIN CWSRS1.CLIENT_T CLT ON CLT.IDENTIFIER = ONM.FKCLIENT_T