DROP VIEW CWSRS1.VW_LST_OTHER_CLIENT_NAME;

CREATE VIEW CWSRS1.VW_LST_OTHER_CLIENT_NAME (
	THIRD_ID, 
	FIRST_NAME, 
	LAST_NAME, 
	MIDDLE_NAME, 
	NAME_PREFIX,
	NAME_TYPE_CODE, 
	NAMW_SUFFIX, 
	LAST_UPDATED_ID, 
	LAST_UPDATED_TIMESTAMP, 
	CLIENT_ID, 	
	IBMSNAP_OPERATION, 
	IBMSNAP_LOGMARKER,
	CLIENT_SENSITIVITY_IND,
	LAST_CHG
) AS 
SELECT 
	ONM.THIRD_ID AS THIRD_ID, 
	ONM.FIRST_NM AS FIRST_NAME, 
	ONM.LAST_NM AS LAST_NAME, 
	ONM.MIDDLE_NM AS MIDDLE_NAME, 
	ONM.NMPRFX_DSC AS NAME_PREFIX,
	ONM.NAME_TPC AS NAME_TYPE_CODE, 
	ONM.SUFX_TLDSC AS NAMW_SUFFIX, 
	ONM.LST_UPD_ID AS LAST_UPDATED_ID, 
	ONM.LST_UPD_TS AS LAST_UPDATED_TIMESTAMP, 
	ONM.FKCLIENT_T AS CLIENT_ID, 	
	ONM.IBMSNAP_OPERATION AS IBMSNAP_OPERATION, 
	ONM.IBMSNAP_LOGMARKER AS IBMSNAP_LOGMARKER,
	CLT.SENSTV_IND AS CLIENT_SENSITIVITY_IND,
	MAX(ONM.IBMSNAP_LOGMARKER, CLT.IBMSNAP_LOGMARKER) LAST_CHG
FROM CWSRS1.OCL_NM_T ONM
JOIN CWSRS1.CLIENT_T CLT ON CLT.IDENTIFIER = ONM.FKCLIENT_T