-- DROP VIEW CWDSDSM.VW_MQT_REFRL_ONLY ;

CREATE VIEW CWDSDSM.VW_MQT_REFRL_ONLY (
	REFERRAL_ID,
	START_DATE,
	END_DATE,
	REFERRAL_RESPONSE_TYPE,
	LIMITED_ACCESS_CODE,
	LIMITED_ACCESS_DATE,
	LIMITED_ACCESS_DESCRIPTION,
	LIMITED_ACCESS_GOVERNMENT_ENT,
	REFERRAL_LAST_UPDATED,
	REPORTER_ID,
	REPORTER_FIRST_NM,
	REPORTER_LAST_NM,
	REPORTER_LAST_UPDATED,
	WORKER_ID,
	WORKER_FIRST_NM,
	WORKER_LAST_NM,
	WORKER_LAST_UPDATED,
	REFERRAL_COUNTY,
	LAST_CHG
) AS 
SELECT 
	RFL.IDENTIFIER        AS REFERRAL_ID,
	RFL.REF_RCV_DT        AS START_DATE,
	RFL.REFCLSR_DT        AS END_DATE,
	RFL.RFR_RSPC          AS REFERRAL_RESPONSE_TYPE,
	RFL.LMT_ACSSCD        AS LIMITED_ACCESS_CODE,
	RFL.LMT_ACS_DT        AS LIMITED_ACCESS_DATE,
	TRIM(RFL.LMT_ACSDSC)  AS LIMITED_ACCESS_DESCRIPTION,
	RFL.L_GVR_ENTC        AS LIMITED_ACCESS_GOVERNMENT_ENT,
	RFL.LST_UPD_TS        AS REFERRAL_LAST_UPDATED,
	RPT.FKREFERL_T        AS REPORTER_ID,
	TRIM(RPT.RPTR_FSTNM)  AS REPORTER_FIRST_NM,
	TRIM(RPT.RPTR_LSTNM)  AS REPORTER_LAST_NM,
	RPT.LST_UPD_TS        AS REPORTER_LAST_UPDATED,
	STP.IDENTIFIER        AS WORKER_ID,
	TRIM(STP.FIRST_NM)    AS WORKER_FIRST_NM,
	TRIM(STP.LAST_NM)     AS WORKER_LAST_NM,
	STP.LST_UPD_TS        AS WORKER_LAST_UPDATED,
	RFL.GVR_ENTC          AS REFERRAL_COUNTY,
	CURRENT TIMESTAMP     AS LAST_CHG
FROM (SELECT DISTINCT rc1.FKREFERL_T FROM CWDSDSM.GT_REFR_CLT rc1) RC
JOIN CWSRS1.REFERL_T          RFL  ON RFL.IDENTIFIER = RC.FKREFERL_T
LEFT JOIN CWSRS1.REPTR_T      RPT  ON RPT.FKREFERL_T = RFL.IDENTIFIER
LEFT JOIN CWSRS1.STFPERST     STP  ON RFL.FKSTFPERST = STP.IDENTIFIER
;


-- CREATE ALIAS CWSRSQ.VW_MQT_REFRL_ONLY FOR CWDSDSM.VW_MQT_REFRL_ONLY;
-- GRANT SELECT ON CWSRSQ.VW_MQT_REFRL_ONLY TO CWSPEF;
-- GRANT SELECT ON CWSRSQ.VW_MQT_REFRL_ONLY TO CWDSDSM;

