DROP VIEW CWSRS1.VW_REFR_CLT;

CREATE VIEW CWSRS1.VW_REFR_CLT ( FKREFERL_T, FKCLIENT_T, SENSTV_IND ) AS 
SELECT rc.FKREFERL_T, rc.FKCLIENT_T, c.SENSTV_IND
FROM CWSRS1.REFR_CLT rc
JOIN CWSRS1.CLIENT_T c  on c.IDENTIFIER = rc.FKCLIENT_T;
