--DROP TABLE CWSRSQ.CMP_CLIENT;


-- Prefer custom tablespace from DBA.

CREATE TABLE CWSRSQ.CMP_CLIENT (
	IDENTIFIER CHAR(10)    PRIMARY KEY NOT NULL,
	SS_NO      VARCHAR(9)  NOT NULL,
	SENSTV_IND CHAR(1)     NOT NULL,
	BIRTH_DT   DATE,
	COM_FST_NM VARCHAR(20) NOT NULL,
	COM_LST_NM VARCHAR(25) NOT NULL,
	COM_MID_NM VARCHAR(20) NOT NULL,
	NMPRFX_DSC VARCHAR(6)  NOT NULL,
	NAME_TPC   SMALLINT    NOT NULL,
	SUFX_TLDSC VARCHAR(4)  NOT NULL,
	GENDER_CD  CHAR(1)     NOT NULL,
	P_ETHNCTYC SMALLINT    NOT NULL,
	P_LANG_TPC SMALLINT    NOT NULL,
	S_LANG_TC  SMALLINT    NOT NULL,
	EMAIL_ADDR VARCHAR(50),
	CREATN_DT  DATE        NOT NULL,
	LST_UPD_ID CHAR(3)     NOT NULL,
	LST_UPD_TS TIMESTAMP   NOT NULL
)
AUDIT NONE
DATA CAPTURE NONE
NOT LOGGED
COMPRESS YES
APPEND YES
--PARTITION BY (IDENTIFIER) (
	--PARTITION 1  ENDING AT ('CpE9999999'),
	--PARTITION 2  ENDING AT ('EE99999998'),
	--PARTITION 3  ENDING AT ('GUE9999997'),
	--PARTITION 4  ENDING AT ('I999999996'),
	--PARTITION 5  ENDING AT ('LpE9999995'),
	--PARTITION 6  ENDING AT ('NE99999994'),
	--PARTITION 7  ENDING AT ('PUE9999993'),
	--PARTITION 8  ENDING AT ('R999999992'),
	--PARTITION 9  ENDING AT ('UpE9999991'),
	--PARTITION 10 ENDING AT ('WE99999990'),
	--PARTITION 11 ENDING AT ('YUE999999Z'),
	--PARTITION 12 ENDING AT ('099999999Y'),
	--PARTITION 13 ENDING AT ('3pE999999X'),
	--PARTITION 14 ENDING AT ('5E9999999W'),
	--PARTITION 15 ENDING AT ('7UE999999V'),
	--PARTITION 16 ENDING AT ('9999999999')
--)
;

SET CURRENT DEGREE = 'ANY' ;


INSERT INTO CWSRSQ.CMP_CLIENT (IDENTIFIER, SS_NO, SENSTV_IND, BIRTH_DT, COM_FST_NM, COM_LST_NM, COM_MID_NM, NMPRFX_DSC, NAME_TPC, SUFX_TLDSC, GENDER_CD, P_ETHNCTYC, P_LANG_TPC, S_LANG_TC, EMAIL_ADDR, CREATN_DT, LST_UPD_ID, LST_UPD_TS)
SELECT
	IDENTIFIER,
	SS_NO,
	SENSTV_IND,
	BIRTH_DT,
	COM_FST_NM,
	COM_LST_NM,
	COM_MID_NM,
	NMPRFX_DSC,
	NAME_TPC,
	SUFX_TLDSC,
	GENDER_CD,
	P_ETHNCTYC,
	P_LANG_TPC,
	S_LANG_TC,
	EMAIL_ADDR,
	CREATN_DT,
	LST_UPD_ID,
	LST_UPD_TS 
FROM CWSRSQ.CLIENT_T;

commit;

-- Create *after* INSERT.

CREATE UNIQUE INDEX CWSRSQ.UIX_CMP_CLIENT ON CWSRSQ.CMP_CLIENT (IDENTIFIER, SENSTV_IND) 
--PARTITIONED CLOSE NO COPY NO DEFER NO DEFINE YES
;


commit;


