package gov.ca.cwds.data.persistence.cms;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.fail;
import static org.mockito.Mockito.mock;

import java.io.Serializable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

import org.junit.Test;

import gov.ca.cwds.data.persistence.cms.rep.CmsReplicationOperation;
import gov.ca.cwds.data.persistence.cms.rep.ReplicatedClient;

public class EsClientAddressTest {

  @Test
  public void type() throws Exception {
    // TODO auto-generated by JUnit Helper.
    assertThat(EsClientAddress.class, notNullValue());
  }

  @Test
  public void instantiation() throws Exception {
    // TODO auto-generated by JUnit Helper.
    EsClientAddress target = new EsClientAddress();
    assertThat(target, notNullValue());
  }

  @Test
  public void strToRepOp_Args__String() throws Exception {
    // TODO auto-generated by JUnit Helper.
    // given
    String op = null;
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    CmsReplicationOperation actual = EsClientAddress.strToRepOp(op);
    // then
    // e.g. : verify(mocked).called();
    CmsReplicationOperation expected = null;
    assertThat(actual, is(equalTo(expected)));
  }

  @Test
  public void extractFromResultSet_Args__ResultSet() throws Exception {
    // TODO auto-generated by JUnit Helper.
    // given
    ResultSet rs = mock(ResultSet.class);
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    EsClientAddress actual = EsClientAddress.extractFromResultSet(rs);
    // then
    // e.g. : verify(mocked).called();
    EsClientAddress expected = null;
    assertThat(actual, is(equalTo(expected)));
  }

  @Test
  public void extractFromResultSet_Args__ResultSet_T__SQLException() throws Exception {
    // TODO auto-generated by JUnit Helper.
    // given
    ResultSet rs = mock(ResultSet.class);
    // e.g. : given(mocked.called()).willReturn(1);
    try {
      // when
      EsClientAddress.extractFromResultSet(rs);
      fail("Expected exception was not thrown!");
    } catch (SQLException e) {
      // then
    }
  }

  @Test
  public void getNormalizationClass_Args__() throws Exception {
    // TODO auto-generated by JUnit Helper.
    EsClientAddress target = new EsClientAddress();
    // given
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    Class<ReplicatedClient> actual = target.getNormalizationClass();
    // then
    // e.g. : verify(mocked).called();
    Class<ReplicatedClient> expected = null;
    assertThat(actual, is(equalTo(expected)));
  }

  @Test
  public void normalize_Args__Map() throws Exception {
    // TODO auto-generated by JUnit Helper.
    EsClientAddress target = new EsClientAddress();
    // given
    Map<Object, ReplicatedClient> map = new HashMap<Object, ReplicatedClient>();
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    ReplicatedClient actual = target.normalize(map);
    // then
    // e.g. : verify(mocked).called();
    ReplicatedClient expected = null;
    assertThat(actual, is(equalTo(expected)));
  }

  @Test
  public void getNormalizationGroupKey_Args__() throws Exception {
    // TODO auto-generated by JUnit Helper.
    EsClientAddress target = new EsClientAddress();
    // given
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    Object actual = target.getNormalizationGroupKey();
    // then
    // e.g. : verify(mocked).called();
    Object expected = null;
    assertThat(actual, is(equalTo(expected)));
  }

  @Test
  public void getPrimaryKey_Args__() throws Exception {
    // TODO auto-generated by JUnit Helper.
    EsClientAddress target = new EsClientAddress();
    // given
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    Serializable actual = target.getPrimaryKey();
    // then
    // e.g. : verify(mocked).called();
    Serializable expected = null;
    assertThat(actual, is(equalTo(expected)));
  }

  @Test
  public void hashCode_Args__() throws Exception {
    // TODO auto-generated by JUnit Helper.
    EsClientAddress target = new EsClientAddress();
    // given
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    int actual = target.hashCode();
    // then
    // e.g. : verify(mocked).called();
    int expected = 0;
    assertThat(actual, is(equalTo(expected)));
  }

  @Test
  public void equals_Args__Object() throws Exception {
    // TODO auto-generated by JUnit Helper.
    EsClientAddress target = new EsClientAddress();
    // given
    Object obj = null;
    // e.g. : given(mocked.called()).willReturn(1);
    // when
    boolean actual = target.equals(obj);
    // then
    // e.g. : verify(mocked).called();
    boolean expected = false;
    assertThat(actual, is(equalTo(expected)));
  }

}
