--==========================
-- TEST TRIGGERS: COLTRL_T:
--==========================

-------------
-- EXISTS: 
-------------

BEGIN ATOMIC

	DECLARE v_tgt_id char(10);
	DECLARE v_src_id char(10);
	DECLARE v_op     char(1);
	DECLARE v_chg    char(1);

	SET v_tgt_id = 'AarHGUP0Ki';
	SET v_src_id = 'AcnyTzu09x'; -- test re-insert
	
	UPDATE CWSINT.COLTRL_T r
	SET 
	    r.FRG_ADRT_B   = 'Y',
	    r.LST_UPD_ID   = '0x5',
	    r.LST_UPD_TS   = current timestamp
	WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.FRG_ADRT_B FROM CWSRS1.COLTRL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'U' OR v_chg != 'Y') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: update existing';
	END IF;

	DELETE FROM CWSINT.COLTRL_T r WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.FRG_ADRT_B FROM CWSRS1.COLTRL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'D' OR v_chg != 'Y') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: delete existing';
	END IF;

	INSERT INTO CWSINT.COLTRL_T (IDENTIFIER, BADGE_NO, CITY_NM, EMPLYR_NM, FAX_NO, FIRST_NM, FRG_ADRT_B, LAST_NM, MID_INI_NM, NMPRFX_DSC, PRM_TEL_NO, PRM_EXT_NO, STATE_C, STREET_NM, STREET_NO, SUFX_TLDSC, ZIP_NO, LST_UPD_ID, LST_UPD_TS, ZIP_SFX_NO, COMNT_DSC, GENDER_CD, BIRTH_DT, MRTL_STC, EMAIL_ADDR, ESTBLSH_CD, ESTBLSH_ID, RESOST_IND)
	SELECT 
	    v_tgt_id as IDENTIFIER,
		BADGE_NO, CITY_NM, EMPLYR_NM, FAX_NO, FIRST_NM, FRG_ADRT_B, LAST_NM, MID_INI_NM, NMPRFX_DSC, PRM_TEL_NO, PRM_EXT_NO, STATE_C, STREET_NM, STREET_NO, SUFX_TLDSC, ZIP_NO, LST_UPD_ID, LST_UPD_TS, ZIP_SFX_NO, COMNT_DSC, GENDER_CD, BIRTH_DT, MRTL_STC, EMAIL_ADDR, ESTBLSH_CD, ESTBLSH_ID, RESOST_IND
	FROM CWSINT.COLTRL_T x
	WHERE x.IDENTIFIER = v_src_id ;
	
	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.FRG_ADRT_B FROM CWSRS1.COLTRL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'I') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: insert existing';
	END IF;

END;


rollback;


-------------
-- NEW: 
-------------

BEGIN ATOMIC

	DECLARE v_tgt_id  char(10);
	DECLARE v_src_id  char(10);
	DECLARE v_op      char(1);
	DECLARE v_chg     char(1);

	SET v_tgt_id = 'Bieber6XXX';
	SET v_src_id = 'AattSTp01T'; -- test re-insert
	
	INSERT INTO CWSINT.COLTRL_T (IDENTIFIER, BADGE_NO, CITY_NM, EMPLYR_NM, FAX_NO, FIRST_NM, FRG_ADRT_B, LAST_NM, MID_INI_NM, NMPRFX_DSC, PRM_TEL_NO, PRM_EXT_NO, STATE_C, STREET_NM, STREET_NO, SUFX_TLDSC, ZIP_NO, LST_UPD_ID, LST_UPD_TS, ZIP_SFX_NO, COMNT_DSC, GENDER_CD, BIRTH_DT, MRTL_STC, EMAIL_ADDR, ESTBLSH_CD, ESTBLSH_ID, RESOST_IND)
	SELECT 
	    v_tgt_id as IDENTIFIER,
		BADGE_NO, CITY_NM, EMPLYR_NM, FAX_NO, FIRST_NM, FRG_ADRT_B, LAST_NM, MID_INI_NM, NMPRFX_DSC, PRM_TEL_NO, PRM_EXT_NO, STATE_C, STREET_NM, STREET_NO, SUFX_TLDSC, ZIP_NO, LST_UPD_ID, LST_UPD_TS, ZIP_SFX_NO, COMNT_DSC, GENDER_CD, BIRTH_DT, MRTL_STC, EMAIL_ADDR, ESTBLSH_CD, ESTBLSH_ID, RESOST_IND
	FROM CWSINT.COLTRL_T x
	WHERE x.IDENTIFIER = v_src_id ;
		
	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.FRG_ADRT_B FROM CWSRS1.COLTRL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'I') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: insert new';
	END IF;

	UPDATE CWSINT.COLTRL_T r
	SET 
	    r.FRG_ADRT_B   = 'Y',
	    r.LST_UPD_ID   = '0x5',
	    r.LST_UPD_TS   = current timestamp
	WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.FRG_ADRT_B FROM CWSRS1.COLTRL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'U' OR v_chg != 'Y') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: update new';
	END IF;

	DELETE FROM CWSINT.COLTRL_T r WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.FRG_ADRT_B FROM CWSRS1.COLTRL_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'D') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: delete new';
	END IF;

END;


rollback;




