--==========================
-- TEST TRIGGERS: CASE_T:
--==========================

-------------
-- EXISTS: 
-------------

BEGIN ATOMIC

	DECLARE v_tgt_id char(10);
	DECLARE v_src_id char(10);
	DECLARE v_op     char(1);
	DECLARE v_chg    char(1);

	SET v_tgt_id = 'M8kVBqs01w';
	SET v_src_id = 'M8p3sGJ0AB'; -- test re-insert
	
	UPDATE CWSINT.CASE_T r
	SET 
	    r.CSPL_DET_B   = 'Y',
	    r.LST_UPD_ID   = '0x5',
	    r.LST_UPD_TS   = current timestamp
	WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CSPL_DET_B FROM CWSRS1.CASE_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'U' OR v_chg != 'Y') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: update existing';
	END IF;

	DELETE FROM CWSINT.CASE_T r WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CSPL_DET_B FROM CWSRS1.CASE_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'D' OR v_chg != 'Y') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: delete existing';
	END IF;

	INSERT INTO CWSINT.CASE_T (IDENTIFIER, START_DT, SRV_CMPC, APRVL_NO, APV_STC, CLS_RSNC, CSPL_DET_B, CL_STM_TXT, CNTRY_C, NOTES_DOC, END_DT, GVR_ENTC, ICPCSTAT_B, ICPC_RQT_B, LMT_ACSSCD, CASE_NM, PRJ_END_DT, SPRJ_CST_B, STATE_C, TICKLE_T_B, LST_UPD_ID, LST_UPD_TS, FKCHLD_CLT, SRV_CMPDT, FKSTFPERST, CNTY_SPFCD, ALERT_TXT, FKREFERL_T, RSP_AGY_CD, NXT_TILPDT, EMANCPN_DT, L_GVR_ENTC, LMT_ACS_DT, LMT_ACSDSC)
	SELECT 
	    v_tgt_id as IDENTIFIER,
		START_DT, SRV_CMPC, APRVL_NO, APV_STC, CLS_RSNC, CSPL_DET_B, CL_STM_TXT, CNTRY_C, NOTES_DOC, END_DT, GVR_ENTC, ICPCSTAT_B, ICPC_RQT_B, LMT_ACSSCD, CASE_NM, PRJ_END_DT, SPRJ_CST_B, STATE_C, TICKLE_T_B, LST_UPD_ID, LST_UPD_TS, FKCHLD_CLT, SRV_CMPDT, FKSTFPERST, CNTY_SPFCD, ALERT_TXT, FKREFERL_T, RSP_AGY_CD, NXT_TILPDT, EMANCPN_DT, L_GVR_ENTC, LMT_ACS_DT, LMT_ACSDSC
	FROM CWSINT.CASE_T x
	WHERE x.IDENTIFIER = v_src_id ;
	
	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CSPL_DET_B FROM CWSRS1.CASE_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'I') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: insert existing';
	END IF;

END;


rollback;


-------------
-- NEW: 
-------------

BEGIN ATOMIC

	DECLARE v_tgt_id  char(10);
	DECLARE v_src_id  char(10);
	DECLARE v_op      char(1);
	DECLARE v_chg     char(1);

	SET v_src_id = 'M8kVBqs01w';
	SET v_tgt_id = '9p291jX96s';
	
	INSERT INTO CWSINT.CASE_T (IDENTIFIER, START_DT, SRV_CMPC, APRVL_NO, APV_STC, CLS_RSNC, CSPL_DET_B, CL_STM_TXT, CNTRY_C, NOTES_DOC, END_DT, GVR_ENTC, ICPCSTAT_B, ICPC_RQT_B, LMT_ACSSCD, CASE_NM, PRJ_END_DT, SPRJ_CST_B, STATE_C, TICKLE_T_B, LST_UPD_ID, LST_UPD_TS, FKCHLD_CLT, SRV_CMPDT, FKSTFPERST, CNTY_SPFCD, ALERT_TXT, FKREFERL_T, RSP_AGY_CD, NXT_TILPDT, EMANCPN_DT, L_GVR_ENTC, LMT_ACS_DT, LMT_ACSDSC)
	SELECT 
	    v_tgt_id as IDENTIFIER,
		START_DT, SRV_CMPC, APRVL_NO, APV_STC, CLS_RSNC, CSPL_DET_B, CL_STM_TXT, CNTRY_C, NOTES_DOC, END_DT, GVR_ENTC, ICPCSTAT_B, ICPC_RQT_B, LMT_ACSSCD, CASE_NM, PRJ_END_DT, SPRJ_CST_B, STATE_C, TICKLE_T_B, LST_UPD_ID, LST_UPD_TS, FKCHLD_CLT, SRV_CMPDT, FKSTFPERST, CNTY_SPFCD, ALERT_TXT, FKREFERL_T, RSP_AGY_CD, NXT_TILPDT, EMANCPN_DT, L_GVR_ENTC, LMT_ACS_DT, LMT_ACSDSC
	FROM CWSINT.CASE_T x
	WHERE x.IDENTIFIER = v_src_id ;
		
	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CSPL_DET_B FROM CWSRS1.CASE_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'I') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: insert new';
	END IF;

	UPDATE CWSINT.CASE_T r
	SET 
	    r.CSPL_DET_B   = 'Y',
	    r.LST_UPD_ID   = '0x5',
	    r.LST_UPD_TS   = current timestamp
	WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CSPL_DET_B FROM CWSRS1.CASE_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'U' OR v_chg != 'Y') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: update new';
	END IF;

	DELETE FROM CWSINT.CASE_T r WHERE r.IDENTIFIER = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CSPL_DET_B FROM CWSRS1.CASE_T r WHERE r.IDENTIFIER = v_tgt_id);
	IF (v_op != 'D') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: delete new';
	END IF;

END;


rollback;




