--==========================
-- TEST TRIGGERS: REPTR_T:
--==========================

-------------
-- EXISTS: 
-------------

BEGIN ATOMIC

	DECLARE v_tgt_id char(10);
	DECLARE v_src_id char(10);
	DECLARE v_op     char(1);
	DECLARE v_chg    char(1);

	SET v_tgt_id = 'AbiQCgu0Hj';
	SET v_src_id = 'AbFA2mz0Ki'; -- test re-insert
	
	UPDATE CWSINT.REPTR_T r
	SET 
	    r.CNFWVR_IND   = 'M',
	    r.LST_UPD_ID   = '0x5',
	    r.LST_UPD_TS   = current timestamp
	WHERE r.FKREFERL_T = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CNFWVR_IND FROM CWSRS1.REPTR_T r WHERE r.FKREFERL_T = v_tgt_id);
	IF (v_op != 'U' OR v_chg != 'M') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: update existing';
	END IF;

	DELETE FROM CWSINT.REPTR_T r WHERE r.FKREFERL_T = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CNFWVR_IND FROM CWSRS1.REPTR_T r WHERE r.FKREFERL_T = v_tgt_id);
	IF (v_op != 'D' OR v_chg != 'M') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: delete existing';
	END IF;

	INSERT INTO CWSINT.REPTR_T (FKREFERL_T,RPTR_BDGNO,RPTR_CTYNM,COL_RELC,CMM_MTHC,CNFWVR_IND,FDBACK_DOC,RPTR_EMPNM,FEEDBCK_DT,FB_RQR_IND,RPTR_FSTNM,RPTR_LSTNM,MNRPTR_IND,MSG_EXT_NO,MSG_TEL_NO,MID_INI_NM,NMPRFX_DSC,PRM_TEL_NO,PRM_EXT_NO,STATE_C,RPTR_ST_NM,RPTR_ST_NO,SUFX_TLDSC,RPTR_ZIPNO,LST_UPD_ID,LST_UPD_TS,FKLAW_ENFT,ZIP_SFX_NO,CNTY_SPFCD)
	SELECT 
	    v_tgt_id as FKREFERL_T,
		RPTR_BDGNO,RPTR_CTYNM,COL_RELC,CMM_MTHC,CNFWVR_IND,FDBACK_DOC,RPTR_EMPNM,FEEDBCK_DT,FB_RQR_IND,RPTR_FSTNM,RPTR_LSTNM,MNRPTR_IND,MSG_EXT_NO,MSG_TEL_NO,MID_INI_NM,NMPRFX_DSC,PRM_TEL_NO,PRM_EXT_NO,STATE_C,RPTR_ST_NM,RPTR_ST_NO,SUFX_TLDSC,RPTR_ZIPNO,LST_UPD_ID,LST_UPD_TS,FKLAW_ENFT,ZIP_SFX_NO,CNTY_SPFCD
	FROM CWSINT.REPTR_T x
	WHERE x.FKREFERL_T = v_src_id ;
	
	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CNFWVR_IND FROM CWSRS1.REPTR_T r WHERE r.FKREFERL_T = v_tgt_id);
	IF (v_op != 'I') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: insert existing';
	END IF;

END;


rollback;


-------------
-- NEW: 
-------------

BEGIN ATOMIC

	DECLARE v_tgt_id  char(10);
	DECLARE v_src_id  char(10);
	DECLARE v_op      char(1);
	DECLARE v_chg     char(1);

	SET v_tgt_id = '02iU6I6XXX';
	SET v_src_id = 'AbFA2mz0Ki'; -- test re-insert
	
	INSERT INTO CWSINT.REPTR_T (FKREFERL_T,RPTR_BDGNO,RPTR_CTYNM,COL_RELC,CMM_MTHC,CNFWVR_IND,FDBACK_DOC,RPTR_EMPNM,FEEDBCK_DT,FB_RQR_IND,RPTR_FSTNM,RPTR_LSTNM,MNRPTR_IND,MSG_EXT_NO,MSG_TEL_NO,MID_INI_NM,NMPRFX_DSC,PRM_TEL_NO,PRM_EXT_NO,STATE_C,RPTR_ST_NM,RPTR_ST_NO,SUFX_TLDSC,RPTR_ZIPNO,LST_UPD_ID,LST_UPD_TS,FKLAW_ENFT,ZIP_SFX_NO,CNTY_SPFCD)
	SELECT 
	    v_tgt_id as FKREFERL_T,
		RPTR_BDGNO,RPTR_CTYNM,COL_RELC,CMM_MTHC,CNFWVR_IND,FDBACK_DOC,RPTR_EMPNM,FEEDBCK_DT,FB_RQR_IND,RPTR_FSTNM,RPTR_LSTNM,MNRPTR_IND,MSG_EXT_NO,MSG_TEL_NO,MID_INI_NM,NMPRFX_DSC,PRM_TEL_NO,PRM_EXT_NO,STATE_C,RPTR_ST_NM,RPTR_ST_NO,SUFX_TLDSC,RPTR_ZIPNO,LST_UPD_ID,LST_UPD_TS,FKLAW_ENFT,ZIP_SFX_NO,CNTY_SPFCD
	FROM CWSINT.REPTR_T x
	WHERE x.FKREFERL_T = v_src_id ;
	
	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CNFWVR_IND FROM CWSRS1.REPTR_T r WHERE r.FKREFERL_T = v_tgt_id);
	IF (v_op != 'I') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: insert new';
	END IF;

	UPDATE CWSINT.REPTR_T r
	SET 
	    r.CNFWVR_IND   = 'M',
	    r.LST_UPD_ID   = '0x5',
	    r.LST_UPD_TS   = current timestamp
	WHERE r.FKREFERL_T = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CNFWVR_IND FROM CWSRS1.REPTR_T r WHERE r.FKREFERL_T = v_tgt_id);
	IF (v_op != 'U' OR v_chg != 'M') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: update new';
	END IF;

	DELETE FROM CWSINT.REPTR_T r WHERE r.FKREFERL_T = v_tgt_id ;

	SET (v_op, v_chg) = (SELECT r.IBMSNAP_OPERATION, r.CNFWVR_IND FROM CWSRS1.REPTR_T r WHERE r.FKREFERL_T = v_tgt_id);
	IF (v_op != 'D') THEN
		SIGNAL SQLSTATE '70002'
		SET MESSAGE_TEXT = 'Failed: delete new';
	END IF;

END;


rollback;




